### ISSUE TITLE
Please add a "YoureAnIdiot" tag to avoid wasting time with trolls.

### ISSUE THREAD

**Issue by ahiotech-alpub** [ministero-salute/it-dgc-verificaC19-android#104]
I suggest to add a new tag for issues like "YoureAnIdiot" to avoid to waste time with pointless issues like: 

#101 
#97 
#94 
#88 

As an alternative, close those issues as they appear. 
Thanks for all the fish.

**Comment by astagi** [comment]
@ahiotech-alpub sure, I'll close the issues you mentioned
