### ISSUE TITLE
Misleading validation text for UK QR Codes

### ISSUE THREAD

**Issue by cesaregardito** [ministero-salute/it-dgc-verificaC19-android#111]
## Describe the bug

When a UK QR code is scanned, the app treats it exactly like an EU Digital Covid Certificate. If it finds one dose of a two-dose vaccine, it says the pass is valid only in Italy. If it finds two doses, it says the pass is valid in Italy and Europe.
However, not all european countries recognize the NHS Covid Pass (UK) as equivalent to the EUDCC. 

## Expected behaviour

The app should correctly identify the QR code as a valid two-doses vaccine certificate from the UK (or other types), and inform the user that it is valid in Italy and in *some* european countries that chose to accept the pass, but not all.

## Steps to reproduce the issue

Scan any NHS Covid Pass (two doses)

## Possible Fix

Change the wording when the issuing country is the UK

## Suggested Text
**Certificazione valida in Italia e in alcuni paesi Europei**
Cosa si può fare con la certificazione verde COVID-19 _(same as the original)_
Attenzione! Il pass britannico 🇬🇧 è riconosciuto solo da alcuni paesi dell'Unione Europea. _(small, orange font)_

**Comment by astagi** [comment]
@cesaregardito I reported this problem to the team, in the next version the app is going to specify it using something like 

“il QR è valido in Italia e in Europa, ma per l’Europa l’utente deve verificare i criteri di accettazione del paese di destinazione”
