### ISSUE TITLE
Northern Ireland QR Codes not valid

### ISSUE THREAD

**Issue by erenato** [ministero-salute/it-dgc-verificaC19-android#114]
## Describe the bug
When I scan my Northern Ireland issued NHS QR code with the app, I receive the error message "Certificazione non valida", despite UK QR codes now being accepted.

## Expected behaviour
The QR code should be valid in line with other UK codes.

## Steps to reproduce the issue
Scan an Northern Ireland QR code.

## Possible Fix
Perhaps the NI code has a different key to the rest of the UK, it may be a case of obtaining these keys to convert it into an EU-accepted certificate.

**Comment by seanquinn** [comment]
Does the team know if it’s a public keys issue or possibly some difference to how the NI QR codes are generated?

**Comment by erenato** [comment]
I have got in touch with the Northern Ireland authorities who issue the code. They have said that they have provided the public keys to the UK Foreign and Commonwealth Office for dissemination to other countries so it is a public keys issue.

**Comment by erenato** [comment]
Hey guys, I am going to close this issue - have tested it out this morning and Northern Ireland QR codes work so keys must have been added. Thank you for your work on this.
