### ISSUE TITLE
1st dose UK NHS QR codes not recognised

### ISSUE THREAD

**Issue by indexicalism** [ministero-salute/it-dgc-verificaC19-android#115]
## Describe the bug
**EDIT** For those who have only the first dose, the app does recognize the QR code and says "Certificazione valida solo in Italia" (as it should be). So the bug only concerns the 1st dose QR code on the UK covid pass for those who have got both doses. In this case, only the QR code for the second jab works, and if trying to scan the code for the first dose the app says "Certificazione non valida".

The app only recognises 2nd dose QR codes, but some people have only the 1st dose which should be equipollente according to the government guidelines.

## Expected behaviour
The app should have accepted the QR code for 1st dose of UK administered vaccine. 

## Technical details

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
Validate also 1st dose QR code.

**Comment by gbonfiglio** [comment]
The "edit" note is not consistent with my experience. I have a 1st dose only GP from NHS UK, and I'm getting a red light from the italian verifier app.

**Comment by indexicalism** [comment]
Indeed, upon further investigation it looks like the issue is with the set "expiration date" of the first dose for mRNA vaccines which in Italy is set at 42 days. Unfortunately this is in contrast with UK's policy of administering the second jab after 8 weeks, so effectively people who have received only the first dose and were unable to get the second before the 8 weeks (I speak from experience) would be discriminated in Italy right now.

**Comment by gbonfiglio** [comment]
This would make sense. My first dose was on 28/6 and I tried on 12/8. Does this effectively mean we're stuck in a limbo between the 43rd day after the first dose and the 15th day after the second?

This would be about 1/2 months based on NHS' current practice of administering the second dose between 8 and 12 weeks after the first one.

To make things even more complex, it's unclear which alternatives do we have. People registered to the italian health authority can get a GP by means of testing, but I guess it's based on them being somewhat registered to whichever tracking system they use, which isn't true for foreigners.

**Comment by cesaregardito** [comment]
@indexicalism the "Equipollenza" circular explicitly says that the validity of the vaccines is the same as the one set in Italy, which means in particular that the first dose of an mRNA vaccine is only valid for 42 days. 

I understand that, given the UK policy of delaying the second dose to 8 weeks, this can be a problem... but, I am afraid, the app is behaving correctly in this instance, recognizing an older-than-42-days first dose QR code as expired.

**Comment by dgrilli** [comment]
I know this is an issue about the first dose but to notice that the app doesn't read anymore the second dose as well. The app is totally broken with the NHS Qr code

**Comment by cesaregardito** [comment]
I do not think so. Kindly follow usual troubleshooting steps such as
renewing your NHS QR code (expires every 30 days), updating the app, etc.

**Comment by dgrilli** [comment]
> every

Thanks for your reply.
Unfortunately any of the usual troubleshooting steps don't work for me.
App version 1.1.2, installed and reinstalled. QR code with expiration date 14 of November, scanned either directly from the NHS app or downloaded new in pdf format... Tested 2 different qr codes of two different people. Also tested my qr code with 3 different phones (android and apple).

Denis

**Comment by FranceBB** [comment]
I can confirm the bug.
I've been denied entry to my workplace today due to the QR Code being considered invalid.
Once the QR code was scanned, the app showed my name, surname and the date of birth, then "invalid" (the red screen) despite the code generated by the NHS App was perfectly valid, showing my second jab of the Oxford Astra Zeneca vaccine administered on the 26th of July 2021. I was also able to reproduce the bug on multiple Android mobile devices.

Please fix this
