### ISSUE TITLE
I got this error when build app

### ISSUE THREAD

**Issue by nhatphamhitechltd** [ministero-salute/it-dgc-verificaC19-android#116]
## Describe the bug

Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///Users/macos/Documents/Works/LivioPomi-covid19/it-dgc-verificaC19-android/app/build/reports/tests/testDebugUnitTest/index.html

## Expected behaviour

Just can run app

## Technical details

- Mac
-

**Comment by Enrico204** [comment]
Any clue in `file:///Users/macos/Documents/Works/LivioPomi-covid19/it-dgc-verificaC19-android/app/build/reports/tests/testDebugUnitTest/index.html` file?

**Comment by nhatphamhitechltd** [comment]
i solved it. Thank you
