### ISSUE TITLE
UK QR passes validation

### ISSUE THREAD

**Issue by Lorenzo-Venturelli** [ministero-salute/it-dgc-verificaC19-android#119]
Are the KIDs (and the relative certificates) associated to UK passes provided by the Italian backend.
In other words, does the app need to send GET requests to another endpoint to separately fetch UK certificates in order to validate UK passes or not?

**Comment by astagi** [comment]
@Lorenzo-Venturelli UK certificates are validated and trusted using UK public keys. These keys are fetched by Italian servers and distributed to verification apps during "keys updating" process. You can get more info from [our documentation](https://github.com/ministero-salute/it-dgc-documentation). Hope this solves your doubts!
