### ISSUE TITLE
Enabling front camera for QR scanning

### ISSUE THREAD

**Issue by cemeroce** [ministero-salute/it-dgc-verificaC19-android#120]
Ability to choose the camera to be used for scanning QR code VerificaC19 - Android
## Problem and motivation

VerificaC19 don't let you choose the camera for scanning QR code. By default works only on retro camera of Android devices.
I would like to use front camera on a tablet device that should be fixed to the wall instead of being used by keeping on hands.
I cannot find a way.

## Is this something you're interested in working on

 No because is not my job but I need it.

**Comment by pocchioni** [comment]
I think this feature is very util for a massive verification as it will be necessary to do from next October 15th.
