### ISSUE TITLE
Manual update button for database and rules

### ISSUE THREAD

**Issue by cesaregardito** [ministero-salute/it-dgc-verificaC19-android#122]
## Feature description
I would like a manual trigger to update "dati e regole". It would be implemented as a "refresh" button in the "Dati e Regole" box. This would not replace the automatic periodic update, just enhance it.

## Problem and motivation
At the moment the update only triggers every once in a while. I get the reason (not overloading servers), but sometimes this can be an issue when certificates have been generated only a few minutes earlier, and the user wants to check the validity via the app.

I got my green pass AUTHCODE at 1:30pm today, and I opened the app to check the downloaded QR code at 1:33pm. It was "invalid". I opened the app on another phone at 1:44pm and it was valid. Despite this, I was unable to trigger an update on the original phone, which kept scanning it as invalid for 15 more minutes.
Now, after 30 minutes, both phones recognize it as valid, due to the first one having updated the "Dati e Regole" database, so that was indeed the issue.

This issue is especially relevant for those that rely on a "48 hour" EUDCC for travel: for instance, many airports offer Covid-19 tests right before departure, and the inability to trigger a database update at will could cause delays at the gates when the EUDCC is checked right after having been generated.

## Is this something you're interested in working on
No

**Comment by lcimaglia** [comment]
Hi
this is a design choice and the reason for this is, as you also declared, avoiding servers overloading

this should not affect DCC QR code validation though. The issue you experienced could be cause by an inconsistent state of VerificaC19 we could investigate on. 
However clearing the app cache should solve the issue.
