### ISSUE TITLE
Verifica validità del certificato in un dato range di tempo

### ISSUE THREAD

**Issue by fabioalbani** [ministero-salute/it-dgc-verificaC19-android#123]
## Current Implementation

Attualmente l'applicazione verifica la validità del certificato per la data odierna (in realtà quella corrente del telefono), non potendo esporre per ragione di privacy la data di scadenza.

## Suggested Enhancement
Nel caso di validità del certificato, segnalare se sarà ancora valido dopo un dato range di tempo, poniamo un mese. Questo dovrebbe garantire la privacy, in quanto sapere ad esempio che dopo un mese un pass non sarà valido non comporta necessariamente di ottenere se si tratta di pass ottenuto tramite tampone, guarigione o vaccino.

## Expected Benefits
Permettere controlli agevoli soprattutto per situazioni dove le persone permangono per un lungo tempo, es. Personale scolastico, clienti degli alberghi...ecc

**Comment by Enrico204** [comment]
Premetto che non conosco le motivazioni dietro alla decisione di non mostrare la data di scadenza.

Credo che mostrare un range così ampio non risolva il problema. Il tampone dura solo 48h, dunque dire che il green pass vale per un mese o no è chiaramente una indicazione di vaccino/guarigione o tampone (almeno fino a quando i primi che si saranno vaccinati non arriveranno a 48h dalla scadenza, ovvero tra parecchi mesi). E anche indicare che dura 48h o no è un problema, dato che, di nuovo, per altri 9 mesi chi ha un green pass in scadenza in meno di 48h è sicuramente per tampone.

Potenzialmente bisognerebbe portare il range ad un numero di mesi tale per cui tampone, guarigione o vaccino diventano indistinguibili, ovvero circa 9 mesi ad oggi (considerando l'estensione di validità a 12 mesi). Solo che probabilmente diventa inutile (secondo me).

**Comment by astagi** [comment]
@Enrico204 dice bene.

In accordo con il team la sintesi è che non si può mostrare la data di scadenza per 2 motivi:

1) Identificherebbe il tipo di green pass
2) La data scadenza è calcolata di volta in volta in base alle regole e le regole cambiano. Quindi non ha senso dire che il green pass scade tra 3 mesi.
