### ISSUE TITLE
Ultimo aggiornamento dati e regole / Last updated data and rules

### ISSUE THREAD

**Issue by superasty** [ministero-salute/it-dgc-verificaC19-android#124]
Ho provato a fare il clone dell'app e compilarla con Android studio. La compilazione va a buon fine, ma, non riesce ad aggiornare dati e regole, guardando i log compare

W/a4.sogei.it/...: type=1400 audit(0.0:240): avc: denied { write } for name="perfd" dev="dm-5" ino=73766 scontext=u:r:untrusted_app_29:s0:c155,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=it.ministerodellasalute.verificaC19
D/OkHttp: --> GET https://testaka4.sogei.it/v1/dgc/signercertificate/status
    User-Agent: DGCA verifier Android 30, sdk_gphone_x86;
    Cache-Control: no-cache
    --> END GET
D/OkHttp: <-- 403 Forbidden https://testaka4.sogei.it/v1/dgc/signercertificate/status (34ms)

Come se venga rifiutata la richiesta.

Come posso fare per risolvere il problema?
Grazie

I tried to clone the app and compile with android studio. The compilation is successful, but fails to update data and rules, looking at the logs appears 

W/a4.sogei.it/...: type=1400 audit(0.0:240): avc: denied { write } for name="perfd" dev="dm-5" ino=73766 scontext=u:r:untrusted_app_29:s0:c155,c256,c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0 app=it.ministerodellasalute.verificaC19
D/OkHttp: --> GET https://testaka4.sogei.it/v1/dgc/signercertificate/status
    User-Agent: DGCA verifier Android 30, sdk_gphone_x86;
    Cache-Control: no-cache
    --> END GET
D/OkHttp: <-- 403 Forbidden https://testaka4.sogei.it/v1/dgc/signercertificate/status (34ms)

As if the request is refused.

How can I go about solving the problem?
Thanks

**Comment by astagi** [comment]
Grazie @ilGimmy aggiungo questa parte nel README.
