### ISSUE TITLE
Add optional webhook after QR code validation

### ISSUE THREAD

**Issue by dario-locci** [ministero-salute/it-dgc-verificaC19-android#126]
## Feature description
Add a webhook to a configurable URL after the validation phase. The content of the webhook could be simply `valid` or `not_valid`.

## Problem and motivation
Some environments demand a more automated way for Green Pass verification, mainly to perform an action based on the output of the validation process (validated, not_validated).

The output of a webhook could be a good starting point to prevent the emerging of not Privacy Compliant solutions in the market. At the moment there is not a straightforward and at the same time simple compliant way to do so using VerificaC19, so it could be a feature to simplify this process.

## Is this something you're interested in working on

No

**Comment by dario-locci** [comment]
Introducing Intents (as #68 describes) could be another solution.

**Comment by astagi** [comment]
Yes, you're right! As I said in #68 the discussion is still open. Maybe an official SDK will be released, or intents support will be provided. I'll close this issue to keep things cleaner, for more needs and ideas we can continue discussion in #68 thread.
