### ISSUE TITLE
Applicazione Linee guida riuso

### ISSUE THREAD

**Issue by lamefrog** [ministero-salute/it-dgc-verificaC19-android#128]
## Your Question

* Source File:
* Line(s):
* Question:

Per quale ragione il codice non è presente tra quelli messi a riuso dalle PA sul catalogo di Developers Italia 
così come prevedono le linee guida AgID che attuano quanto previsto dagli articoli 68 e 69 del CAD?

**Comment by astagi** [comment]
@lamefrog publiccode.yml aggiunto. Faccio anche per iOS e mettiamo a catalogo.
