### ISSUE TITLE
Permettere a Smartphone con Android 6 e 7 di scaricare l'app

### ISSUE THREAD

**Issue by lamefrog** [ministero-salute/it-dgc-verificaC19-android#129]
## Feature description

Attualmente per caricare l'app è prevista la presenza di Android 8 o successivi e questo taglia fuori un gran numero di smartphone dalla possibilità di scaricare l'app.

Visto che app similari come quella svizzera (che verifica senza problemi i green pass italiani) prevedono di potere essere scaricate anche con Android 6, si suggerisce di aggiornare il codice per permettere anche ai possessori di smartphone con Android 6 e 7 di scaricare l'app.

Il progetto svizzero è raggiungibile al seguente indirizzo:
[https://github.com/admin-ch/CovidCertificate-App-Android](https://github.com/admin-ch/CovidCertificate-App-Android)

**Comment by astagi** [comment]
Ciao @lamefrog si, stiamo lavorando e testando proprio sui device con Android 6 e 7.

- PR #113 #71 
- Issue di riferimento #95 

Chiudo come duplicato

**Comment by precy79** [comment]
Da settembre ad ora ancora nessun supporto per Android 6 o 7 quando i palmari venduti profumatamente con applicazioni del genere hanno tutti android 6.0.1!!!
