### ISSUE TITLE
Info 

### ISSUE THREAD

**Issue by superasty** [ministero-salute/it-dgc-verificaC19-android#132]
Quando l'app si collega al server del ministero, che dati scarica o invia?
Grazie
Fabio

**Comment by berdav** [comment]
Ciao, non ho informazioni "ufficiali" e nemmeno "ufficiose", ma leggendo il codice sembra che l'app scarichi solo le configurazioni dall'endpoint.  Vediamo se arriva qualche risposta piu' dettagliata dagli sviluppatori.

Queste configurazioni comprendono le varie scadenze dei vari green pass a seconda della tipologia e del vaccino, la versione minima dell'app abilitata alla verifica e la lista dei certificati crittografici che possono validare l'autenticita' dei gp.  Non e' presente una lista di certificati revocati.

Non mi pare che vengano inviati dati (intesi come dati applicativi, ovviamente viene fatta la richiesta al server, quindi le varie informazioni di rete vengono inviate come il tuo indirizzo ip pubblico, etc etc).  Mi sorprenderebbe alquanto.

Le informazioni scaricate le puoi trovare su:

https://get.dgc.gov.it/v1/dgc/settings (le impostazioni e le scadenze)
https://get.dgc.gov.it/v1/dgc/signercertificate/status (la lista dei certificati con i quali l'app fa caching)
https://get.dgc.gov.it/v1/dgc/signercertificate/update (i vari certificati, questo e' solo il primo, puoi ottenere gli altri cambiando un header nella richiesta HTTP)

Non sono a conoscenza di altri endpoint utilizzati.

Ciao,
D.

**Comment by astagi** [comment]
Ciao @superasty! Gli endpoint descritti da @berdav (che ringrazio per il supporto) sono esatti. Maggiori info [qua](https://github.com/ministero-salute/it-dgc-documentation/blob/master/openapi.yaml).

**Comment by superasty** [comment]
Grazie!!!
