### ISSUE TITLE
App does not accept NHS Scotland QR code

### ISSUE THREAD

**Issue by MichalBryxi** [ministero-salute/it-dgc-verificaC19-android#135]
## Describe the bug

On scanning my NHS **Scotland** QR code I get following screen saying "Certificazione non valida":

![Photo on 16-09-2021 at 08 07](https://user-images.githubusercontent.com/847473/133566273-3d23f6da-9c57-4a38-a845-246645feae27.jpg)

## Expected behaviour

Since [NHS certificates are deemed valid](https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/102), I'd expect NHS *Scotland* be also accepted.

## Steps to reproduce the issue

Scan a QR code issued by NHS *Scotland*.

## Technical details

- Android 11
- App version: 1.1.0 (updated on: 9. Aug 2021), which [seems to have](https://github.com/ministero-salute/it-dgc-verificaC19-android/releases/tag/1.1.0) the [patch mentioned above](https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/102)

## Additional notes

I was able to load my certificate to Swiss version of the app (still claiming it's invalid) and the details I see are:

![photo_2021-09-16 08 16 49](https://user-images.githubusercontent.com/847473/133567643-f434a52c-42c8-403a-889e-e84dbb9346ec.jpeg)

![photo_2021-09-16 08 16 46](https://user-images.githubusercontent.com/847473/133567644-13e09c1f-2d42-4946-9e92-d81cb0eb41b1.jpeg)

- I redacted the URN as I don't have the knowledge whether that is a private information or not.
- I can share the QR codes for examination. I assume those are private information and should not be uploaded to GitHub.

**Comment by MichalBryxi** [comment]
Just realised:

- I don't have a control NHS England QR code to check that the app actually accepts NHS England codes.
- I am happy to share additional data (even the scan of the whole NHS Scotland certificate) once someone gives me confirmation that these are ok to share (I don't really care about publishing my name or DOB, but am worried about someone using my covid passport)

**Comment by gwr3n** [comment]
I can confirm I am facing the same issue. Please note that NHS Scotland is a separate body from NHS England, so it is likely to use a different key/signature.

**Comment by gwr3n** [comment]
If it can be of any help, I believe the body in charge of producing NHS Scotland COVID passes is www.nss.nhs.scot they are quite active on Twitter @NHSNSS

**Comment by BonjoDan** [comment]
I don't know if it can help. Just to let you know. The app on the Apple Store called "NHS Scotland COVID Check" developed by NHS Education for Scotland is working perfectly (naturally). Here the link: 

https://apps.apple.com/gb/app/nhs-scotland-covid-check/id1583924545

Let me know if I can hep in some way.

**Comment by MichalBryxi** [comment]
That might eventually help @BonjoDan, thank you. I can't find Android version though. Do you have a clue?

**Comment by BonjoDan** [comment]
Maybe this one?

 https://play.google.com/store/apps/details?id=scot.nhs.nss.checkin&hl=en_US&gl=US

**Comment by BonjoDan** [comment]
I have an Android phone as well so I can test it.

**Comment by BonjoDan** [comment]
No, sorry. Unfortunately it seems a different app.

**Comment by astagi** [comment]
@gwr3n @BonjoDan @MichalBryxi DSC uploaded to production env. I made some tests and everything works as expected! 🏴󠁧󠁢󠁳󠁣󠁴󠁿
