### ISSUE TITLE
Problema nella build

### ISSUE THREAD

**Issue by acaliaro** [ministero-salute/it-dgc-verificaC19-android#141]
## Describe the bug
Cercando di effettuare la build con

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.andrey4623.rainbowcsv, Lombook Plugin, com.symbol.emdk.wizardex, net.seesharpsoft.intellij.plugins.csv, Dart, org.jetbrains.kotlin, io.flutter

Ho questo errore:
ould not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :decoder.
     Required by:
         project :app
      > No matching configuration of project :decoder was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

Il progetto it-dcf-verificaC19-android e dgca-app-core-android si trovano nella stessa directory

## Expected behaviour
Il progetto dovrebbe compilare

## Technical details

- Host Machine OS (Windows/Linux/Mac): Windows 10

**Comment by JoeyElRassi** [comment]
i am having the same issue, any luck in solving it?

**Comment by carlo318** [comment]
See the Build doc here:   
https://github.com/ministero-salute/it-dgc-verificaC19-android

**Comment by acaliaro** [comment]
Le direttive indicate nella Build sono state seguite. I due progetti sono nella stessa directory allo stesso livello, ma il problema persiste. Facendo la build del "verifica", appare l'errore riportato. C'è una soluzione? Grazie

**Comment by carlo318** [comment]
Con le App in 3 cartelle tutte allo stesso livello, a me compila.

`|___ dgca-app-core-android`
`|___ dgca-verifier-app-android`
`|___ it-dgc-verificaC19-intent`

**Comment by acaliaro** [comment]
Senza fare alcuna modifica a gradle o al progetto Android Studio?

**Comment by JoeyElRassi** [comment]
senza nessuna modifica deve funzionare

**Comment by acaliaro** [comment]
riuscite a mandarmi uno zip delle vostre cartelle? Così cerco di capire le differenze...

**Comment by JoeyElRassi** [comment]
non me lo fa mandare.. cmq io le ho scaricate come sono da qua, poi messi insieme in una cartella tipo C:/projects/androidapps/c19
per compilare bastano i folder dgca-app-core-android e it-dgc-verificaC19  (dgca-verifier-app-android serve allo stesso livello per poter fare le verifiche ma non per compilare)
In android studio apri solo il progetto it-dgc-verificaC19 e compila (si mette un bel po) ma poi ti deve funzionare

**Comment by stefanoq21** [comment]
@acaliaro   controlla il nome delle cartelle, scaricandole ti aggiunge il branch nel nome. Controlla che siano precisamente così:
|___ dgca-app-core-android
|___ it-dgc-verificaC19-intent
