### ISSUE TITLE
Validità app C19 - Validity C19

### ISSUE THREAD

**Issue by superasty** [ministero-salute/it-dgc-verificaC19-android#145]
Buongiorno, è possibile inviare in remoto il dato letto?

Attualmente in Italia l'unico metodo per validare il green pass è l'app C19... se viene modificata per inviare i dati è ancora ritenuta valida?

Hello, is it possible to send the read data remotely?

Currently in Italy the only method to validate the green pass is the C19 app ... if it is modified to send the data is it still considered valid?

Fabio

**Comment by astagi** [comment]
Ciao @superasty no app VerificaC19 non invia in remoto nessun dato, il suo funzionamento dopo aver scaricato regole e chiavi pubbliche può avvenire completamente offline
