### ISSUE TITLE
Automatic close results after desired time

### ISSUE THREAD

**Issue by pocchioni** [ministero-salute/it-dgc-verificaC19-android#146]
## Current Implementation
After a certificate read the app show the result until the close button is pressed

## Suggested Enhancement
An option that allows you to choose a viewing time of your choice

## Expected Benefits
In order to use the app with an automatic recognition system.
It would also be useful to be able to use the front camera

**Comment by EdossProject** [comment]
Salve, è già stata effettuata questa funzione? Possiamo attivarla in qualche modo? Avrei necessità che si auto chiudesse.

**Comment by EdossProject** [comment]
aggiornamenti?

**Comment by lcimaglia** [comment]
Hi
we are experimenting on a feature like this but the front camera seems a bit low quality in order to achieve a fast QR scanning.
So at the moment we are thinking whether this feature would be useful or not.

**Comment by EdossProject** [comment]
> Hi we are experimenting on a feature like this but the front camera seems a bit low quality in order to achieve a fast QR scanning. So at the moment we are thinking whether this feature would be useful or not.

hi actually i am wondering regarding automatic closing after scan and if possible go back directly to scan and not to ACTIVITY FIRST

**Comment by EdossProject** [comment]
> As I said we are currently working on this

Sorry, How many time?
