### ISSUE TITLE
Dove si trova il pacchetto dgc-sdk.

### ISSUE THREAD

**Issue by RobertoPucci** [ministero-salute/it-dgc-verificaC19-android#158]
Il software necessita del progetto dgc-sdk.
infatti in fase di  Build viene restituito l'errore:
Could not determine the dependencies of task ':app:lintDebug'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :dgc-sdk.
     Required by:
         project :app
     .....

Grazie

**Comment by rawmain** [comment]
Ciao @RobertoPucci 

> Il software necessita del progetto dgc-sdk. infatti in fase di Build viene restituito l'errore: Could not determine the dependencies of task ':app:lintDebug'.

La repository [it-dgc-verificac19-sdk-android](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android) è ancora impostata come privata.

Una volta passata a pubblica, potrai aggiungerla in modo da avere l'ok con le impostazioni di settings.gradle per i progetti esterni = la seguente struttura delle directory.

``` 
android-app
|___it-dgc-verificaC19-android
|___dgca-app-core-android
|___it-dgc-verificac19-sdk-android
```
