### ISSUE TITLE
Impossibile compilare l'app sul branch MAIN

### ISSUE THREAD

**Issue by nicetomytyuk** [ministero-salute/it-dgc-verificaC19-android#159]
Sto provando a buildare l'app dal branch main ma la compilazione fallisce con il seguente stacktrace:

```
Build file 'E:\Android\VisualVerifier\dgca-app-core-android\decoder\build.gradle' line: 45

A problem occurred evaluating project ':decoder'.
> No such property: desugar_jdk_libs for class: Deps

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
[stacktrace-12102021.txt](https://github.com/ministero-salute/it-dgc-verificaC19-android/files/7331284/stacktrace-12102021.txt)

Dentro la cartella VisualVerifier sono presenti i due progetti dgca-app-core-android e it-dgc-verificaC19-android.

Tutto ciò che ho fatto è clonare i due progetti, aprire it-dgc-verificaC19-android e provare a fare la build sul branch main.

**Comment by rawmain** [comment]
Ciao @nicetomytyuk 

> Sto provando a buildare l'app dal branch main ma la compilazione fallisce con il seguente stacktrace:
[...]
> > No such property: desugar_jdk_libs for class: Deps
[...]
> Tutto ciò che ho fatto è clonare i due progetti, aprire it-dgc-verificaC19-android e provare a fare la build sul branch main.

Controllando il [tuo fork](https://github.com/nicetomytyuk/it-dgc-verificaC19-android), vedo comunque che alcune branch non risultano aggiornate / allineate correttamente con i rispettivi storici commit della repo ufficiale.

Vale anche per la tua branch main ed ecco perché non trova in Dependencies.kt la definizione di desugar_jdk_libs .

Riallineando correttamente le tue branch, non riscontrerai più tale errore.

**Comment by nicetomytyuk** [comment]
> Ciao @nicetomytyuk
> 
> > Sto provando a buildare l'app dal branch main ma la compilazione fallisce con il seguente stacktrace:
> > [...]
> > > No such property: desugar_jdk_libs for class: Deps
> > > [...]
> > > Tutto ciò che ho fatto è clonare i due progetti, aprire it-dgc-verificaC19-android e provare a fare la build sul branch main.
> 
> Controllando il [tuo fork](https://github.com/nicetomytyuk/it-dgc-verificaC19-android), vedo comunque che alcune branch non risultano aggiornate / allineate correttamente con i rispettivi storici commit della repo ufficiale.
> 
> Vale anche per la tua branch main ed ecco perché non trova in Dependencies.kt la definizione di desugar_jdk_libs .
> 
> Riallineando correttamente le tue branch, non riscontrerai più tale errore.

Ciao @rawmain il branch era indietro di 1 commit siccome durante il fork tale non esisteva ancora, però da tuo suggerimento ho provato a fare un fetch in entrambi i branch ma gli stessi errori persistono, questo invece è lo stacktrace del branch develop:

```
Could not determine the dependencies of task ':app:testDebugUnitTest'.
> Could not resolve all task dependencies for configuration ':app:debugUnitTestRuntimeClasspath'.
   > Could not resolve project :dgc-sdk.
     Required by:
         project :app
      > No matching configuration of project :dgc-sdk was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
```
L'unico che sono riuscito a far partire senza problemi per adesso è il branch 1.1.2

**Comment by rawmain** [comment]
Ciao @nicetomytyuk

> il branch era indietro di 1 commit siccome durante il fork tale non esisteva ancora, però da tuo suggerimento ho provato a fare un fetch in entrambi i branch ma gli stessi errori persistono

Procedendo al diff/compare delle tue forked branch vedo però ancora un disallineamento maggiore a livello di storico modifiche/commit per alcune, e quindi di codice. 

Alcune sono even (_e.g. release/1.1.2 - corrispondente al ramo della release su Play Store e AppGallery - che infatti hai compilato senza errori_), ma altre no (_e.g. main_).

Se il tuo intento fosse comunque quello di avere un allineamento completo branch, l'ideale sarebbe procedere a questo punto con eliminazione forked repo + nuovo fork, in modo da riportarsi in condizioni even per il sync delle varie branch.

.
> questo invece è lo stacktrace del branch develop:
[...]
>    > Could not resolve project :dgc-sdk.
>      Required by:
>          project :app
>       > No matching configuration of project :dgc-sdk was found. 

Da ieri - a seguito anche dell'OK ufficiale del Garante della Privacy - il branch develop è stato allineato all'impostazione delle ultime active branch, cioè l'integrazione con DGC-SDK (_it.ministerodellasalute.verificaC19sdk_).

Tale integrazione prevede appunto l'aggiunta del progetto dgc-sdk (vedasi settings.gradle) con la definizione della seguente struttura per le directory progetto.

``` 
android-app
|___it-dgc-verificaC19-android
|___dgca-app-core-android
|___it-dgc-verificac19-sdk-android
```

La repository associata [it-dgc-verificac19-sdk-android](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android) è ancora impostata come privata = accessibile/utilizzabile solo dal team ufficiale di sviluppo.

Pertanto, o si attende la sua pubblicazione oppure semplicemente ci si arrangia, qualora vi sia esigenza stretta di compilare/testare contestualmente gli aggiornamenti pubblicati dal team nelle active branch.

.
Nelle ultime settimane io ho infatti ovviato temporaneamente, assemblandomi un [SDK "grezzo" di test](https://github.com/VC19tests/VC19-SDK-Test) da usare con accorgimenti minimi, onde poter compilare/testare gli aggiornamenti delle active branch con dependency/integrazione DGC-SDK.

[Questa è p.es. una mia release-build](https://github.com/VC19bkp/it-dgc-verificaC19-android-SDKtest/releases/tag/1.1.2-SDK-Test-API23-01) - _personalizzata solo per supporto minSDK ribassato ad API23 Marshmallow_ - che usa il codice branch develop con integrazione DGC-SDK - allineato fino ai commit di ieri. 

Infatti include già le nuove funzionalità testate/pubblicate nelle ultime settimane dal team ufficiale (ved. totem mode, gestione fotocamere, supporto flash).

**Comment by nicetomytyuk** [comment]
Ciao @rawmain , sei stato chiarissimo, non capisco come mai è successo questo di disallineamento durante il fork anche perché l'ho fatto ieri pomeriggio..

Comunque adesso eseguo nuovamente il fork e darò un'occhiata al tuo SDK

Grazie per l'aiuto 💯
