### ISSUE TITLE
Device con Android 6 e 7 ?

### ISSUE THREAD

**Issue by ik1xpv** [ministero-salute/it-dgc-verificaC19-android#169]
Ciao @lamefrog si, stiamo lavorando e testando proprio sui device con Android 6 e 7.

- PR #113 #71 
- Issue di riferimento #95 

Chiudo come duplicato

_Originally posted by @astagi in https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/129#issuecomment-912635655_

**Comment by ik1xpv** [comment]
Qualche sviluppo o decisione sulla compatibilità con Android 6 e 7   ?
...
https://github.com/ministero-salute/it-dgc-verificaC19-android/issues/169#issue-1028278650
...
https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/71#issue-952066177

Grazie

**Comment by rawmain** [comment]
Ciao @ik1xpv 

> Qualche sviluppo o decisione sulla compatibilità con Android 6 e 7 ?

L'issue di riferimento #95 è ancora aperta, per cui è possibile che questa discussione venga chiusa con redirezione a tale issue.

In ogni caso, per quanto riguarda le attività di sviluppo : 

- L'attuale impostazione develop branch del codice per app (_it.ministerodellasalute.verificaC19_) + DGC-SDK (_it.ministerodellasalute.verificaC19sdk_) prevede nuovamente - _per entrambe le repo_ - l'abilitazione del desugaring per riduzione minSDK ad API 24 Nougat 7.0 ([PR#71](https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/71/files)).
.
Modifiche, che erano state incorporate ad inizio Settembre, ma poi reverted/annullate successivamente, in fase di rilascio della release ufficiale [1.1.2](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/release/1.1.2) & relativa pubblicazione su PlayStore - AppGallery.
.
Pertanto, indipendentemente da minSDK per i singoli moduli dgc-sdk e decoder, non è comunque scontata la conferma del desugaring nel codice per prossima release ufficiale app = come avvenuto per la release 1.1.2, dipenderà ovviamente da quelle, che saranno le valutazioni di staff/team in funzione di test/attività sul codice (_anche in repo private, non solo nelle branch pubbliche_).

----------------

- Il downgrade versione Zxing_core & la dichiarazione esplicita dependency jackson-datatype-jsr310 per riduzione minSDK ad API 23 Marshmallow 6.0 ([PR#113](https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/113/files)) sono compatibili tecnicamente anche con attuale impostazione codice app+DGC-SDK - ved. [ultimi aggiornamenti nel relativo comment-roll](https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/113#issuecomment-942830717).
.
Modifiche ancora (correttamente) in standby review per eventuale incorporazione = vedansi attività/test in corso per BusinessRules + certlogic (integrazione SDK) & conferma o rinvio del desugaring per prossima release ufficiale app.
