### ISSUE TITLE
AGGIORNAMENTI

### ISSUE THREAD

**Issue by EdossProject** [ministero-salute/it-dgc-verificaC19-android#193]
Ciao ragazzi come aggiorno la mia app? I dispositivi in cui l'ho installato chiede update.
Posso disattivare la richiesta di update dallo store?

**Comment by rawmain** [comment]
Ciao @EdossProject 

> I dispositivi in cui l'ho installato chiede update. Posso disattivare la richiesta di update dallo store?

Periodicamente - dopo il rilascio di una nuova versione VerificaC19 - viene aggiornata lato [validation rules](https://get.dgc.gov.it/v1/dgc/settings) la soglia della release minima utilizzabile per le verifiche.

Gli aggiornamenti delle validation rules di ieri hanno alzato il valore soglia APP_MIN_VERSION per la release Android a 1.1.6 = non possono essere più usate le precedenti release 1.1.2 e 1.1.5 (_soglia minima precedente era 1.1.2_), ma solo la 1.1.6 e l'ultima 1.1.7 pubblicata su Google PlayStore / Huawei AppGallery.

Pertanto, disattivando gli aggiornamenti automatici nelle impostazioni Store dei dispositivi, è comunque necessario procedere all'aggiornamento app quando la versione installata risulti anteriore alla release minima - ammessa dagli aggiornamenti delle validation rules.

**Comment by EdossProject** [comment]
Ciao @rawmain 

> Ciao @EdossProject
> 
> > I dispositivi in cui l'ho installato chiede update. Posso disattivare la richiesta di update dallo store?
> 
> Periodicamente - dopo il rilascio di una nuova versione VerificaC19 - viene aggiornata lato [validation rules](https://get.dgc.gov.it/v1/dgc/settings) la soglia della release minima utilizzabile per le verifiche.
> 
> Gli aggiornamenti delle validation rules di ieri hanno alzato il valore soglia APP_MIN_VERSION per la release Android a 1.1.6 = non possono essere più usate le precedenti release 1.1.2 e 1.1.5 (_soglia minima precedente era 1.1.2_), ma solo la 1.1.6 e l'ultima 1.1.7 pubblicata su Google PlayStore / Huawei AppGallery.
> 
> Pertanto, disattivando gli aggiornamenti automatici nelle impostazioni Store dei dispositivi, è comunque necessario procedere all'aggiornamento app quando la versione installata risulti anteriore alla release minima - ammessa dagli aggiornamenti delle validation rules.

Perfetto, come faccio ad aggiornare il mio SDK?

**Comment by rawmain** [comment]
Ciao @EdossProject

> Perfetto, come faccio ad aggiornare il mio SDK?

Gli aggiornamenti delle prodrelease ufficiali Android di VerificaC19 - pubblicate su Google PlayStore / Huawei AppGallery - includono già contestualmente anche gli aggiornamenti dei moduli Android [DGC-SDK](https://github.com/ministero-salute/it-dgc-verificaC19-sdk-android) e [EU-DCC Core Decoder](https://github.com/eu-digital-green-certificates/dgca-app-core-android).

Solo per quanto riguarda le soluzioni/app di terze parti & conformi [Artt. 12 e 13 DPCM 12/10/2021](https://www.governo.it/sites/governo.it/files/DPCM_12_ottobre.pdf) per verifica DGC, che integrano/usano il modulo DGC-SDK Android (_unico autorizzato per ora dal Ministero della Salute - ved. [validazioni in corso di altri SDK/librerie](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/pulls)_), spetta agli sviluppatori di tali soluzioni/app mantenere l'allineamento con gli aggiornamenti SDK rilasciati in produzione.
