### ISSUE TITLE
Super green pass

### ISSUE THREAD

**Issue by lpomi** [ministero-salute/it-dgc-verificaC19-android#202]
## Your Question
Quando e' previsto l'aggiornamento per controllare i certificati secondo le regole del super green pass ? In alcune regioni e' già applicato adesso è non vi e' la possibilità di effettuare il controllo con VerificaC19.

* Source File:
* Line(s):
* Question:

**Comment by rawmain** [comment]
Ciao @lpomi 

> Quando e' previsto l'aggiornamento per controllare i certificati secondo le regole del super green pass ? In alcune regioni e' già applicato adesso è non vi e' la possibilità di effettuare il controllo con VerificaC19.

La pubblicazione store delle nuove prodrelease (sia iOS che Android) VerificaC19 è pianificata prima del 6 Dicembre - in linea con le disposizioni del DL n.172 26/11/2021 (_cui art.5 comma 2 prevede/consente nel transitorio 29/11-05/12 l'effettuazione in deroga delle verifiche SGP vs certificato completo/cartaceo_).

Le attività feature & relative all'implementazione della scelta operatore per scenario/tipologia di verifica 

- Base = 3G - Vaccinazione/Guarigione/Test

- Rafforzata = 2G - Vaccinazione/Guarigione

sono comunque già praticamente definite dopo <7gg = aggiunta pub degli ultimi commit & bump release a 1.1.8 . 

Vedansi gli storici commit delle relative branch feature, che per la versione Android sono :

- [Storico branch feature/super-dgp-ui App/UI Android](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/feature/super-dgp-ui)

- [Storico branch feature/super-dgp-sdk DGC-SDK Android/Kotlin](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/feature/super-dgp-sdk)
