### ISSUE TITLE
Readme steps not working

### ISSUE THREAD

**Issue by vlajkoe** [ministero-salute/it-dgc-verificaC19-android#203]
Can you please update ReadMe, because the steps you wrote in "Build" section do not make the application run.

1. Why don't you have nuget package for Xamarin?

* Source File:
* Line(s):
* Question:

**Comment by nicetomytyuk** [comment]
@vlajkoe can you check the updated readme with steps in **Build**? Let me know if you were able to solve the issue.

**Comment by vlajkoe** [comment]
@nicetomytyuk  yes, thanks

**Comment by astagi** [comment]
Great work @nicetomytyuk !!
