### ISSUE TITLE
Super green pass ancora in branch develop

### ISSUE THREAD

**Issue by lpomi** [ministero-salute/it-dgc-verificaC19-android#210]
Il 6 la nuova versione con super green pass deve essere usata per i controlli degli utenti, quindi deve essere scaricata da Apple store domani per gli aggiornamenti. Come mai e' ancora in branch develop ?
Solo per la pubblicazione su Apple store servono un paio di giorni.
## Your Question

* Source File:
* Line(s):
* Question:

**Comment by rawmain** [comment]
Ciao @lpomi 

> Come mai e' ancora in branch develop ?

Branch update-release - integranti appunto gli aggiornamenti SGP - definite dal 2 Dicembre.

- [App/UI Release 1.1.8 - build 611](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/release/1.1.8)

- [DGC-SDK Android/Kotlin 1.0.4](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.4)

Le submission delle build agli store (_Google PlayStore e Huawei AppGallery per release 1.1.8 - build 611 Android_) sono state effettuate regolarmente in tale data. 

Non vi sono state questioni in fase di review ed infatti gli aggiornamenti (_compresa release 1.1.8 iOS in Apple AppStore n.d.r._) sono già disponibili per il download dagli store mobile sin dal primo pomeriggio odierno.
