### ISSUE TITLE
Info Super GreenPass

### ISSUE THREAD

**Issue by EdossProject** [ministero-salute/it-dgc-verificaC19-android#211]
Ciao ragazzi,
cosa devo aggiornare per il nuovo super green pass?
Che parte di codice è stato aggiornato?
Grazie!

**Comment by rawmain** [comment]
Ciao @EdossProject 

> cosa devo aggiornare per il nuovo super green pass?

Per reproducible-build dei pacchetti prodrelease 1.1.8 pubblicati su PlayStore/AppGallery devi allineare il codice dei progetti alle seguenti branch : 

- **App/UI** : `it-dgc-verificaC19-android` branch [release/1.1.8](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/release/1.1.8)

- **DGC-SDK** : `it-dgc-verificac19-sdk-android` branch [release/1.0.4](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.4)

- **EU DGC Core/Decoder** : `dgca-app-core-android` branch [main](https://github.com/eu-digital-green-certificates/dgca-app-core-android) fino ad ultimo commit (20gg fa) 66b2531

----------------------------

> Che parte di codice è stato aggiornato? Grazie!

Rispetto al codice precedente usato per prodrelease Android 1.1.6/1.1.7 App/UI con Version 1.0.2 DGC-SDK : 

- App/UI & DGC-SDK : aggiunta commit attività 24/11->02/12 per il supporto SGP scanmode 2G/3G

> - [Commit / File Changes App/UI 1.1.6->1.1.8](https://github.com/ministero-salute/it-dgc-verificaC19-android/compare/release/1.1.6...ministero-salute:release/1.1.8)
>
> - [Commit / File Changes DGC-SDK 1.0.2->1.0.4](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/compare/release/1.0.2...release/1.0.4)

- EU DGC Core/Decoder : aggiunta commit 66b2531 rispetto a 1.1.7/SDK1.0.2 || aggiunta commit 8c2872b + 66b2531 rispetto a 1.1.6/SDK1.0.2 

> 1. [Commit 8c2872b EU DGC Core](https://github.com/eu-digital-green-certificates/dgca-app-core-android/commit/8c2872b77efb98c61c4f13fb5bdc6a1edff99716)
>
> 2. [Commit 66b2531 EU DGC Core](https://github.com/eu-digital-green-certificates/dgca-app-core-android/commit/66b25316eda87bad9bf1616f0a7c7f87d9d35a7f)

I commit precedenti per supporto revoke CRL/DRL - seppur già confluiti nelle develop branch App/UI e DGC-SDK - sono stati comunque rinviati per prossima/e release.

**Comment by EdossProject** [comment]
Mi puoi spiegare come fare?
