### ISSUE TITLE
Instructions to rebuilt 1.1.8

### ISSUE THREAD

**Issue by ilGimmy** [ministero-salute/it-dgc-verificaC19-android#212]
## Your Question

Hi,
I need help to rebuild 1.1.8 as published on Play Store.

I checked out:

- it-dgc-verificaC19-android branch release/1.18
- it-dgc-verificac19-sdk-android branch release/1.0.4
- dgca-app-core-android commit 0a9ad293088762a1291655749f6d41608891a360

is it correct?

Thank you
Andrea

**Comment by rawmain** [comment]
Hello @ilGimmy 

> Hi, I need help to rebuild 1.1.8 as published on Play Store.
> 
> I checked out
[...]
> is it correct?

Yes, you've picked the right arrangement for reproducible builds of prodrelease 1.1.8 packages - available from Google Play Store & Huawei AppGallery.

- **App/UI** : `it-dgc-verificaC19-android` branch [release/1.1.8](https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/release/1.1.8)

- **DGC-SDK** : `it-dgc-verificac19-sdk-android` branch [release/1.0.4](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/release/1.0.4)

- **EU DGC Core/Decoder** : `dgca-app-core-android` branch [main](https://github.com/eu-digital-green-certificates/dgca-app-core-android) up to latest commit (20d ago) 66b2531

**Comment by ilGimmy** [comment]
Thank you!
