### ISSUE TITLE
Durata greenpass ancora 12 mesi?

### ISSUE THREAD

**Issue by jumpjack** [ministero-salute/it-dgc-verificaC19-android#214]
Nel file https://get.dgc.gov.it/v1/dgc/settings è ancora indicata la durata di 365 per il greenpass. Non dovrebbero essere 270 (9mesi) dal 6/12/2021?

**Comment by rawmain** [comment]
Ciao @jumpjack 

> Nel file https://get.dgc.gov.it/v1/dgc/settings è ancora indicata la durata di 365 per il greenpass. Non dovrebbero essere 270 (9mesi) dal 6/12/2021?

No = l'unico allineamento JSON Validation Rules richiesto da DL 172 26/11/2021 & con decorrenza da 06/12 era l'innalzamento soglia value 1.1.6->1.1.8 per `APP_MIN_VERSION`, regolarmente effettuato ieri.

La riduzione durata 12->9 mesi per i DGC V 2/2 - 3/2 - booster si applica a decorrere dal **15 Dicembre** ex [Art.3 Comma 2 DL 172 26/11/2021](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=84133&articolo=3).

Pertanto, il cambio 365->270 dei value per `vaccine_end_day_complete` in Validation Rules avverrà entro le 24h precedenti, cioè il 14/12.
