### ISSUE TITLE
Il greenpass da due dosi è ancora valido dopo la terza

### ISSUE THREAD

**Issue by jumpjack** [ministero-salute/it-dgc-verificaC19-android#218]
Non so se sia un errore di programmazione o legislativo, ma a livello logico che senso ha che il greenpass della seconda dose risulti ancora valido dopo che mi è arrivato il greenpass della terza dose?!?
Praticamente se faccio la 3a dose a 5 mesi, per 4 mesi avrò due greenpass validi contemporaneamente?

**Comment by falemagn** [comment]
Sì, due green pass validi contemporaneamente, entrambi rilasciati alla stessa persona, uno dei quali scadrà prima dell'altro. Non vi è motivo di sicurezza sanitaria perché questo sia un problema.

**Comment by nicetomytyuk** [comment]
Non è un problema relativo all'applicazione siccome tale interpreta solamente le informazioni all'interno di questo, la revoca dei greenpass è gestita direttamente dal ministero e credo che è stato più facile per loro adottare una soluzione in cui al rilascio di un nuovo greenpass il vecchio viene invalidato solamente con la sua scadenza, ti consiglio di chiudere la issue quindi.

Penso che non revocare un greenpass vecchio al rilascio di uno nuovo sia anche "comodo" siccome facciamo finta che oggi ti fai la terza dose, nel tuo portafoglio hai il tuo vecchio greenpass stampato (quello da 2 dosi) la sera stessa vai a cenare e ti viene rilasciato il nuovo greenpass quindi il tuo vecchio viene invalidato ma tu hai il telefono scarico...
