### ISSUE TITLE
Instructions to rebuild 1.2.0

### ISSUE THREAD

**Issue by ilGimmy** [ministero-salute/it-dgc-verificaC19-android#223]
## Your Question

Dear team

I'm asking for instructions to perform a custom build of 1.2.0.

it-dgc-verificaC19-android: [tag 1.2.0](https://github.com/ministero-salute/it-dgc-verificaC19-android/releases/tag/1.2.0)
it-dgc-verificac19-sdk-android: [tag 1.1.0](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/releases/tag/1.1.0)
dgca-app-core-android: commit 66b2531 on branch [main](https://github.com/eu-digital-green-certificates/dgca-app-core-android)

is it correct?

Thank you
Andrea

**Comment by rawmain** [comment]
Hello @ilGimmy 

> I'm asking for instructions to perform a custom build of 1.2.0.
> 
> it-dgc-verificaC19-android: [tag 1.2.0](https://github.com/ministero-salute/it-dgc-verificaC19-android/releases/tag/1.2.0)
> it-dgc-verificac19-sdk-android: [tag 1.1.0](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/releases/tag/1.1.0)
> dgca-app-core-android: commit 66b2531 on branch [main](https://github.com/eu-digital-green-certificates/dgca-app-core-android)
> 
> is it correct?

Yes.

You've picked the right tags/branches in order to build reproducible-builds of prodrelease 1.2.0 packages - available from Google Play Store / Huawei AppGallery.
