### ISSUE TITLE
GreenPass Rafforzato

### ISSUE THREAD

**Issue by EdossProject** [ministero-salute/it-dgc-verificaC19-android#224]
Ciao, dopo aver aggiornato tutto mi legge i test (nella versione rafforzata) come validi.
Com'è possibile?

**Comment by rawmain** [comment]
Ciao @EdossProject 

> dopo aver aggiornato tutto mi legge i test (nella versione rafforzata) come validi. Com'è possibile?

Potrebbe esserci stato un problema di ripristino impostazioni app / prefkeys e/o di sync DB locale SQLite sul dispositivo (Rules/KIDS). In assenza di log / altre info queste sono le ipotesi più plausibili.

Se non l'hai già fatto, chiudi l'app, accertandoti da multitasking/recenti che non rimanga in esecuzione. Quindi azzera relative Cache+Dati da Impostazioni / App e riaprila, onde forzare appunto il reset di impostazioni e DB & nuovi fetch Rules + KIDs + CRL. 

Oppure semplicemente rimuovila dal dispositivo & reinstallala da Store.

**Comment by EdossProject** [comment]
Non parliamo dell'app che si trova nello store ma dalla repo che troviamo qui su Git.

**Comment by rawmain** [comment]
Ciao @EdossProject 

> Non parliamo dell'app che si trova nello store ma dalla repo che troviamo qui su Git.

Non ci sono tali problemi, integrando in modo corretto tanto DGC-SDK 1.1.0 quanto successiva release DGC-SDK 1.1.1 .

Essendo quindi un problema specifico di tua app personalizzata/terza, sarebbe utile che postassi riferimenti di tuo codice app/UI e/o estratti debug/logcat. 

In questo modo sarebbe possibile vedere con precisione perché tua app non stesse rilevando/gestendo correttamente il cambio prefkey per scanmode.

**Comment by EdossProject** [comment]
Ho ri-scaricato tutte le reposity e ricompilata l'app, ora funziona. Probabilmente utilizzavo una vecchia versione dell'SDK. Grazie ;)
