### ISSUE TITLE
Verifica "terza dose" per accessi RSA

### ISSUE THREAD

**Issue by baugigi** [ministero-salute/it-dgc-verificaC19-android#232]
## Feature description
L'app dovrebbe consentire di distinguere i green pass rafforzati rilasciati dopo la "terza dose" da quelli rilasciati dopo il solo ciclo vaccinale primario. 

## Problem and motivation
La richiesta di miglioramento è necessaria per il controllo degli accessi in RSA e strutture sociosanitarie secondo le nuove disposizioni (art 7 del DL 221/2021).

**Comment by rawmain** [comment]
Buonasera @baugigi 

> L'app dovrebbe consentire di distinguere i green pass rafforzati rilasciati dopo la "terza dose" da quelli rilasciati dopo il solo ciclo vaccinale primario.
[...]
> La richiesta di miglioramento è necessaria per il controllo degli accessi in RSA e strutture sociosanitarie secondo le nuove disposizioni (art 7 del DL 221/2021).

Le versioni iOS/Android 1.2.1 di VerificaC19 - con appunto l'aggiunta della tipologia di verifica Booster (_Richiamo Vaccinale / Ciclo completo + Tampone / Guarigione + Tampone_) - sono state finalizzate come codice prodrelease il 27 Dicembre (_ved. branch & release/tag_) & sono già anche disponibili per il download dagli store mobile.

L'aggiornamento per Android è stata pubblicato infatti nel pomeriggio odierno su Google PlayStore & Huawei AppGallery, contestualmente a quello per iOS su Apple AppStore.

**Comment by baugigi** [comment]
**La _verifica booster_ della versione 1.2.1 potrebbe avere un bug.** 
Ho provato a verificare un GP di soggetto vaccinato con monodose J&J a cui è stata poi somministrata una dose booster di Pfizer: l'app segnala **erroneamente** "certificato valido - richiesto tampone". 
Notare che nel cartaceo questo GP è indistinguibile da un "semplice" doppia dose Pfizer in quanto riporta dosi fatte/dosi previste=2/2.

**Comment by baugigi** [comment]
Chiudo perché ho avuto notizia che MinSalute sta rilasciando green pass aggiornati con dosi 2/1 per ovviare a questo problema.

**Comment by rawmain** [comment]
> Chiudo perché ho avuto notizia che MinSalute sta rilasciando green pass aggiornati con dosi 2/1 per ovviare a questo problema.

Il caso limite di tali DGC 2/2 non riguarda solo l'Italia, ma anche altri paesi, p.es. Danimarca e soprattutto Germania (che ha usato tale codifica 2/2 come schema predefinito anche per i richiami in modalità eterologa dopo 1° dose Johnson & Johnson).

In data 21 Dicembre è stata approvata la standardizzazione delle codifiche dn/sd per i DGC di richiamo.

https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/93#issuecomment-1001822186

Le nuove regole - incluso allineamento a codifiche standard dn/sd - saranno pienamente effettive a partire dal 1 Febbraio 2022, ma Il Ministero della Salute ha già iniziato appunto le procedure di controllo per tali DGC & emissioni DGC sostitutivi con codifica standard dn/sd 2/1.
