### ISSUE TITLE
Invio risposta ad un dispositivo/pc

### ISSUE THREAD

**Issue by EdossProject** [ministero-salute/it-dgc-verificaC19-android#233]
Salve, sarebbe possibile (una volta letto il greenpass) inviare una Notifica/Un Output ad un PC/Server...

Esempio: 

GreenPass Positivo -> PC Server OK
GreenPass Negativo -> PC Server KO

Tutto qui... Grazie

**Comment by nedex** [comment]
In che modo sarebbe utile per tutti?

**Comment by EdossProject** [comment]
Mi immagino una piantana che legge il greenpass (esempio in un azienda) collegata ad un Arduino che quando riceve OK (apre la sbarra o illumina un LED verde/rosso).

**Comment by EdossProject** [comment]
UP? Aggiornamenti?

**Comment by nicetomytyuk** [comment]
@EdossProject penso che per una modifica del genere il diretto interessato dovrebbe fare un bel fork e farsi la versione customizzata date le proprie necessità..

**Comment by EdossProject** [comment]
Se qualcuno mi dice che parte del codice restituisce quel dato lo faccio volentieri.

**Comment by nicetomytyuk** [comment]
@EdossProject lo stato e i dati vengono restituiti una volta che un certificato è letto dentro `onViewCreated` di `VerificationFragment` nello specifico dentro la sottoscrizione a `viewModel.certificate` quindi dovresti implementare la tua logica proprio in questo punto, altrimenti direttamente dopo la decodifica del certificato in `CodeReaderFragment`.

**Comment by EdossProject** [comment]
> @EdossProject lo stato e i dati vengono restituiti una volta che un certificato è letto dentro `onViewCreated` di `VerificationFragment` nello specifico dentro la sottoscrizione a `viewModel.certificate` quindi dovresti implementare la tua logica proprio in questo punto, altrimenti direttamente dopo la decodifica del certificato in `CodeReaderFragment`.

Presumo  che
if (
                    viewModel.getTotemMode() &&
                    (certificate.certificateStatus == CertificateStatus.VALID)
                ) 

identifichi lo stato valido, dovrei aggiungere un else o c'è gia una voce che lavori sul INVALID?

Grazie per l'aiuto

**Comment by nicetomytyuk** [comment]
@EdossProject non proprio, quell'IF entra nel gioco solo quando il `TotemMode `è settato su true quindi attenzione, controlla tutto il codice nel blocco come `setPersonData` per capire come si comporta con i vari stati il fragment.

Comunque puoi semplicemente aggiungere nel blocco una funzione dove gli passi il `certificate` e dove successivamente fai le tue verifiche e le tue chiamate ad Arduino in base se il CertificateStatus è VALID o meno, poi ovviamente è tua la logica che dovresti utilizzare e vedere tu stesso come e dove è meglio implementare il tutto.

**Comment by EdossProject** [comment]
> @EdossProject non proprio, quell'IF entra nel gioco solo quando il `TotemMode `è settato su true quindi attenzione, controlla tutto il codice nel blocco come `setPersonData` per capire come si comporta con i vari stati il fragment.
> 
> Comunque puoi semplicemente aggiungere nel blocco una funzione dove gli passi il `certificate` e dove successivamente fai le tue verifiche e le tue chiamate ad Arduino in base se il CertificateStatus è VALID o meno, poi ovviamente è tua la logica che dovresti utilizzare e vedere tu stesso come e dove è meglio implementare il tutto.

Grazie per le indicazioni. Purtroppo non sono pratico di Kotlin, quindi dovrei creare una PRIVATE FUN che in caso sia VALID invia ad arduino OK altrimenti KO. Corretto?
