### ISSUE TITLE
Cosa scarica adesso ogni giorno l'app?

### ISSUE THREAD

**Issue by jumpjack** [ministero-salute/it-dgc-verificaC19-android#234]
Vedo che adesso l'app richiede di scaricare ogni giorno il db aggiornato. Ma dove risiede questo db? La blacklist su  https://get.dgc.gov.it/v1/dgc/settings è ferma da settimane a soli 2000 greenpass revocati.

**Comment by astagi** [comment]
Ciao @jumpjack si tratta della DRL, maggiori informazioni qua https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md
