### ISSUE TITLE
Controllo Super Green pass per più di 50 anni

### ISSUE THREAD

**Issue by lpomi** [ministero-salute/it-dgc-verificaC19-android#235]
Per fare il controllo oltre 50 anni come si fa ? verrà rilasciata una nuova modalità di controllo oltre a Base, Rafforzata e Booster ?
Sapete se / quando è previsto il rilascio ?

**Comment by rawmain** [comment]
Buongiorno @lpomi 

> Per fare il controllo oltre 50 anni come si fa ? verrà rilasciata una nuova modalità di controllo oltre a Base, Rafforzata e Booster ? Sapete se / quando è previsto il rilascio ?

Per quanto concerne le nuove prescrizioni normative del [Decreto Legge n.1 7 Gennaio 2022](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=84933) : 

- Non sono necessarie modifiche all'[attuale impostazione SCANMODE](https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md) per gestione flussi degli accessi/scenari in cui siano previste le tipologie di verifica Rafforzata o Booster.

- Ancora da definire le istruzioni operative x scenari/accessi luoghi di lavoro con mix obbligo vaccinale (>= 50 anni) e non (<50 anni) - previsti da prescrizioni Art.1 comma 3 DL n.1 07/01/2022, che saranno effettive a partire dal **15 Febbraio**.

Qualora Ministero della Salute & Organi competenti dovessero eventualmente richiedere/indicare un nuovo scanmode dedicato per gli accessi ai luoghi di lavoro, a partire dal 15 Febbraio, differenziando i flussi di validazione in base all'età : 

- meno di 50 anni -> Validazione Base (3G V/R/T)
- 50 anni ed oltre -> Validazione Rafforzata (2G V/R)

basterebbe l'aggiunta del controllo vs data di nascita all'attuale flusso di controlli DGC T (tampone).

**Comment by lpomi** [comment]
Buongiorno,
certo, ma è una logica che deve per forza implementare nativamente l'app VerificaC19 stessa, quindi una scelta del controllo da applicare. Non avrebbe senso chiedere alle persone un documento prima del controllo o rifare i controlli più volte ...

Per i luoghi di lavoro una nuova modalità di controllo scelto sull'app dovrà vedere la data di nascita presente nel certificato green pass e applicare il controllo conseguente Base o Rafforzato.

**Comment by rawmain** [comment]
Buonasera @lpomi 

> ma è una logica che deve per forza implementare nativamente l'app VerificaC19 stessa [...]

Non è detto a priori, dato che dipende appunto da come verranno definiti i passaggi dei controlli operatore per tale scenario.

Pertanto, come già avvenuto per l'implementazione tecnica della tipologia booster, è comunque necessario attendere le procedure attuative / istruzioni operative, che verranno definite & approvate/ufficializzate da Ministero della Salute + organi competenti per i controlli degli accessi ai luoghi di lavoro a partire dal 15 Febbraio.

Saranno infatti solo queste a determinare necessità/entità (o meno) di variazioni tecniche per gestione flussi e/o output esiti di validazione da parte delle verifier-app iOS/Android VerificaC19 & delle app/soluzioni, che integrino/usino DGC-SDK Android/Kotlin - SDK/Librerie terze parti & autorizzate in conformità a DPCM 12/10/2021.

> una nuova modalità di controllo scelto sull'app dovrà vedere la data di nascita presente nel certificato green pass e applicare il controllo conseguente Base o Rafforzato

Il campo 'data di nascita' `dob` è già valorizzato/gestito (_infatti viene mostrato in output esiti_) e l'aggiunta di una relativa condizione di controllo età - _tanto per gestione scenario specifico job da 15/02 quanto per eventuale estensione ad altri scenari con mix tipologie verifica_ - avverrebbe comunque solo a livello del flusso di validazione DGC tipo Test (Tampone) - ved. appunto documentazione scanmode e logiche/codice gestione flussi post scansione/decodifica QR.

La questione non è comunque tecnica di eventuali (minime) modifiche al codice, bensì rimane appunto operativa di definizione/gestione procedure.

Se queste richiederanno interventi lato codice app/SDK, questi verranno ovviamente effettuati per tempo - alla stregua degli interventi precedenti.

**Comment by fabioalbani** [comment]
Stavo giusto ponendomi lo stesso interrogativo ma, anche se probabilmente non è previsto dai DL e DPCM, non sarebbe la migliore soluzione per garantire l'obbligo vaccinale per i maggiori di 50 anni il rendere la verifica base equivalente alla rafforzata per quella categoria di età? Nel senso, dove già c'è il filtro del tampone, non dovrebbe essere escluso a priori per chi è obbligato al vaccino?

**Comment by rawmain** [comment]
Buonasera @fabioalbani 

> dove già c'è il filtro del tampone, non dovrebbe essere escluso a priori per chi è obbligato al vaccino?

No. Il codice verifier-app/SDK deve essere cmq conforme a prescrizioni normative + procedure attuative / istruzioni operative ufficiali.

Una tale restrizione generica per esito validazioni DGC T con scanmode Base NON è appunto contemplata dalle attuali prescrizioni normative per estensione obbligo vaccinale in base all'età - ved. Art. 1 del [Decreto Legge n.1 07/01/2022](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=84933) - nemmeno come misura vs inadempienze post 1° Febbraio.

**Comment by lpomi** [comment]
Buongiorno, 
la modalità scan mode WORK che vedo in lavorazione recepirà anche la logica Over50 o questa sarà successiva / ulteriore evolutiva ?

**Comment by rawmain** [comment]
Buongiorno @lpomi 

> la modalità scan mode WORK che vedo in lavorazione recepirà anche la logica Over50 o questa sarà successiva / ulteriore evolutiva ?

Lo scanmode WORK (Tipologia di verifica Lavoro) implementa appunto la logica test-over-50 per i flussi di validazione dei DGC T (tampone) ed è già stata promosso feature->develop 4h fa (_ved. commit-tracker per develop branch whitelabel-app/UI e DGC-SDK_)

**Comment by lpomi** [comment]
Buongiorno, 
la 1.2.5 con la modalità WORK verrà rilasciata oggi come release ?

**Comment by zubeer95** [comment]
Probabilmente aspettano le 00:30 di questa notte per rilasciare la versione 1.2.5, come anche l'SDK, in questo modo regalano a noi system integrator una bella nottata a fare il deploy sui sistemi aziendali per il controllo automatico... Grazie Sogei/IBM, gentilissimi

**Comment by andrekiba** [comment]
senza parole...non capisco se ancora a livello normativo ci sono dei punti aperti per cui non può essere rilasciata...il giorno prima dell'entrata in vigore di un obbligo di cui si parla da mesi e ancora ci sono cose non chiare??

**Comment by rawmain** [comment]
Buongiorno @andrekiba 

> se ancora a livello normativo ci sono dei punti aperti per cui non può essere rilasciata

Le richieste di ulteriori modifiche - pervenute venerdì - non erano correlate allo scanmode WORK in sé, bensì alle nuove medical rules, che prevedono condizioni addizionali per tutti gli scanmode (_ved. controllo EMA vs NOT_EMA [Art.3 DL n°5/2022 07/02/2022](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=85657&articolo=3)_). Tali hanno comportato purtroppo il delay rispetto alla data preventivata (appunto venerdì) di finalizzazione con attività extra - visibili anche dallo storico commit del weekend nelle feature branch delle repo pub.

Le modifiche relative alla release 1.1.5 del DGC-SDK Android/Kotlin sono state finalizzate solo ieri pomeriggio & approvate 1h fa (ved. anche merge in develop branch). Pertanto, seppur non ancora in tracker pub il relativo tag/release, gli integrator possono già cmq procedere con verifiche integrazione SDK version-update in loro app/soluzioni & effettuare i test in base ai [flussi aggiornati](https://raw.githubusercontent.com/rawmain/it-dgc-documentation/feat/scanmode-work-school-exemption/img/image20E.png).

Per quanto concerne whitelabel-app/UI Android 1.2.5 erano state finalizzate ieri pomeriggio anche le modifiche app/UI - contestualmente a quelle DGC-SDK, ma è stato richiesto revert+edit del design UI (in allineamento alla release iOS). Ecco perché non sono ancora state approvate/merged. Ecco perché sono ancora in corso (sia per iOS che Android) attività relative alla UI.

**Comment by lpomi** [comment]
Grazie, ma non possiamo partire con qualcosa che non sia in release. 
Non lo e' ne SDK ne VerificaC19

**Comment by rawmain** [comment]
Buongiorno

> Grazie

Prego ;).

> non possiamo partire con qualcosa che non sia in release. Non lo e' ne SDK ne VerificaC19

Non ho parlato di rilascio/deploy in produzione, ma di verifiche/test preliminari.

Per quanto riguarda il solo DGC-SDK, mi sono solo limitato a suggerire di avviare - senza attendere che siano pub branch/tag `release/1.1.5` - le verifiche preliminari di integrazione + relativi test, considerando che il relativo codice per gestione nuovi flussi è stato finalizzato+approvato.

Ergo, non dovrebbero esservi differenze tra il codice attualmente in branch develop e quello prodrelease. Alla peggio potrebbero esservi commit/edit minimali di rearrangement, che non comporterebbero comunque la ripetizione dei test = nuove logiche/strategie di validazione sono cmq definite/approvate. 

\
5 minuti fa approvate anche le principali modifiche UI, consentendo quindi l'anticipo delle verifiche preliminari anche a chi effettua deploy delle storerelease ufficiali VerificaC19 o di app terze basate semplicemente su legal-fork whitelabel-app (_semplice sostituzione packageID/nomi/loghi e privacy/terms della whitelabel-app_) + DGC-SDK + EU DGCA Decoder.

Ci sono ancora alcuni commit in valutazione (non rinviati a prossima release whitelabel-app/UI), ma la loro eventuale approvazione non richiederebbe comunque la ripetizione delle verifiche preliminari.

**Comment by andrekiba** [comment]
ok grazie mille @rawmain, sottolineo che ovviamente la "colpa" non è vostra...è il sistema in generale con la richiesta fatta venerdì ad essere assurdo :-)
