### ISSUE TITLE
BUG validità greenpass

### ISSUE THREAD

**Issue by orsi-dev** [ministero-salute/it-dgc-verificaC19-android#241]
## Describe the bug
Abbiamo riscontrato un bug nella validazione del greenpass generato dopo una guarigione da covid per un soggetto non vaccinato. La validità dovrebbe essere di 180 giorni dalla data di emissione ma non viene mai rispettata. 

## Expected behaviour

Osservando la differenza tra la data di emissione e la data di scadenza non risultano rispettati i 180 giorni come da requisito.
I 180 giorni di validità si presentano facendo la differenza tra il primo tampone positivo e la data di scadenza del greenpass.
## Technical details

- Host Machine OS (Windows/Linux/Mac):
- Andoid App

## Possible Fix

Correggere il controllo 👯

**Comment by rawmain** [comment]
Buongiorno @orsi-dev 

> Abbiamo riscontrato un bug nella validazione del greenpass generato dopo una guarigione da covid per un soggetto non vaccinato. La validità dovrebbe essere di 180 giorni dalla data di emissione ma non viene mai rispettata.

Non è un bug.

I DGC type R PV di guarigione post-vaccinazione prevedono attualmente ancora scadenza 270gg (ved. `recovery_pv_cert_end_day` in [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings)). 

Tale valore verrà infatti rimodulato a 180 - in allineamento ai DGC type R - solo a partire dal 1° Febbraio, come previsto da DL.

**Comment by jumpjack** [comment]
Cosa significa "Type R PV"? "R" sta per "Recovery" cioè guarigione, ma "PV"? Vedo che la durata è stata portata a ben 540 giorni, 18 mesi!

```
{"name":"recovery_pv_cert_end_day","type":"GENERIC","value":"540"
{"name":"vaccine_end_day_booster_IT","type":"GENERIC","value":"540"}
```

Sarebbe la cosiddetta "durata infinita"?

**Comment by DevPGS** [comment]
> Cosa significa "Type R PV"? "R" sta per "Recovery" cioè guarigione, ma "PV"? Vedo che la durata è stata portata a ben 540 giorni, 18 mesi!
> 
> ```
> {"name":"recovery_pv_cert_end_day","type":"GENERIC","value":"540"
> {"name":"vaccine_end_day_booster_IT","type":"GENERIC","value":"540"}
> ```
> 
> Sarebbe la cosiddetta "durata infinita"?

Ciao @jumpjack,
guardando sopra si legge
> I DGC type *R PV* di **guarigione post-vaccinazione** prevedono attualmente ancora scadenza ......

quindi R PV dovrebbe essere l'acronimo di Recovery Post-Vaccinazione

**Comment by jumpjack** [comment]
Ah giusto, Recovery Post-Vaccine.
