### ISSUE TITLE
Controllo della vaccinazione/guarigione nei 120 giorni

### ISSUE THREAD

**Issue by pablitocalvo** [ministero-salute/it-dgc-verificaC19-android#246]
## Feature description

l'app dovrebbe segnalare (nel caso di controllo di green pass rafforzato) se la vaccinazione/guarigione è avvenuta nei 120 giorni precedenti.

## Problem and motivation

Nelle scuole sono in vigore regole che permettono agli studenti di frequentare in presenza anche a fronte di compagni di classe positivi se vaccinati/guariti da meno di 120 giorni.
Poiché alle scuole è ora dato il permesso di conoscere lo stato vaccinale degli studenti, ma non memorizzarlo, devono fare un controllo quotidiano. Poichè il green pass ha validità 9 mesi ( 6 dal 1 febbraio) ammetterebbero in classe  alunni indebitamente, quindi per evitare ciò dovrebbero controllare con l'app (per verificare l'eventuale revoca) e poi controllare manualmente il certificato  per il calcolo dei 120 giorni. 
È evidente che questo doppio controllo incentiva a saltarne uno con le conseguenze immaginabili.

## Is this something you're interested in working on
Yes

**Comment by rawmain** [comment]
Buonasera @pablitocalvo 

> l'app dovrebbe segnalare (nel caso di controllo di green pass rafforzato) se la vaccinazione/guarigione è avvenuta nei 120 giorni precedenti.
[...]
> Nelle scuole sono in vigore regole [...]

Le attività relative allo scanmode SCHOOL (_Tipologia di Verifica SCUOLA - conforme [Art.4 c.2 DL 01/2022](https://www.trovanorme.salute.gov.it/norme/dettaglioAtto?id=84933&articolo=4)_) - che appunto è dedicato ai controlli per accessi in ambito scuole/istitui - sono visibili pubblicamente dal **13 Gennaio** nelle rispettive feature branch iOS/Android : 

- **DGC-SDK Android** : [feature/school-scan-mode-sdk commits](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commits/feature/school-scan-mode-sdk)

- **iOS** : [feature/school-scan-mode commits](https://github.com/ministero-salute/it-dgc-verificaC19-ios/commits/feature/school-scan-mode)

Non è stato inserito nell'ultima release 1.2.2 - _pubblicata store 26/01 con sola aggiunta del supporto per i certificati digitali di esenzione_ - in virtù della richiesta di alcune modifiche.

L'implementazione di tale nuovo scanmode in produzione è quindi stata posposta. Qualora non fosse ancora possibile renderla disponibile tramite nuovo rilascio entro 01/02, verrebbe comunque rilasciata unitamente al nuovo scanmode WORK (_Tipologia di Verifica LAVORO_) prima del 15/02.

-----------------------------------------

> Poichè il green pass ha validità 9 mesi ( 6 dal 1 febbraio) ammetterebbero in classe alunni indebitamente, quindi per evitare ciò dovrebbero controllare con l'app (per verificare l'eventuale revoca) e poi controllare manualmente il certificato per il calcolo dei 120 giorni.

La modalità di doppio controllo (_1° check QR DGC in Verifica Rafforzata con verifier-app + 2° check esame in presa visione della certificazione cartacea/digitale di vaccinazione_) è proprio disposta ufficialmente per i controlli d'accesso alla didattica in presenza per scuole secondarie I°/II° grado e IeFP, nell’ipotesi in cui in una classe si siano verificati due casi positivi.

In tal senso, è stata anche confermata/approvata dal Garante della Privacy, che ha anche indicato gli adempimenti da parte di operatori/titolari per effettuare correttamente i trattamenti dati in relazione a tali verifiche = ved. [Coronavirus FAQ GPDP Scuola - n° 14](https://www.garanteprivacy.it/temi/coronavirus/faq#scuola).

Pertanto, è'/resta comunque regolarmente utilizzabile sino appunto alla disponibilità in produzione del nuovo scanmode SCHOOL.

**Comment by pablitocalvo** [comment]
Grazie!
