### ISSUE TITLE
Cattura di dati da applicazione in background

### ISSUE THREAD

**Issue by LucaDavolio** [ministero-salute/it-dgc-verificaC19-android#249]
È possibile riuscire, da un'altra applicazione, a "catturare" i dati relativi alla persona e alla validità del certificato, tutto questo senza modificare il codice sorgente dell'applicazione Verifica C19?
O per forza si deve andare ad inserire un "Intent" o chi per questo nel codice del "VerificationFragment"?

**Comment by rawmain** [comment]
Ciao @LucaDavolio 

> È possibile riuscire, da un'altra applicazione, a "catturare" i dati relativi alla persona e alla validità del certificato, tutto questo senza modificare il codice sorgente dell'applicazione Verifica C19? O per forza si deve andare ad inserire un "Intent" o chi per questo nel codice del "VerificationFragment"?

Se per _"catturare"_ intendi intercettare da un'altra app gli output di validazioni effettuate tramite la verifier-app ufficiale VerificaC19, ciò è **esplicitamente vietato da disposizioni/prescrizioni** = normative vigenti ed indicazioni GPDP.

\
Peraltro, da Ottobre sono ampiamente disponibili le risorse necessarie, onde implementare & effettuare in modo corretto/conforme le validazioni DGC con applicazioni di terze parti :

- **Tecniche** = [DGC-SDK Android/Kotlin](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android) in prima battuta e successivamente [SDK/Librerie di terze parti autorizzate dal Ministero della Salute](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding), che possono essere appunto usati legittimamente - _senza apportare modifiche autonome al relativo codice_ - per sviluppo/integrazione app terze.

& 

- **Normative** = termini legali VerificaC19 (_in sintesi, divieto riutilizzo nome/marchi di VerificaC19 in app terze_) + disposizioni e prescrizioni per gestione privacy & trattamento corretto dei dati delle validazioni DGC con app integranti SDK ufficiale / autorizzati - ved. Art. 13 [DPCM 12/10/2021](https://www.governo.it/sites/governo.it/files/DPCM_12_ottobre.pdf) 

> 13. Con riguardo all’uso del pacchetto di sviluppo per applicazioni, di cui al comma 10, lettera a), e delle librerie software e delle soluzioni da esse derivate, di cui al comma 12, il trattamento dei dati personali deve essere effettuato limitatamente alle informazioni pertinenti e alle operazioni strettamente necessarie alla verifica della validità delle Certificazioni verdi COVID-19.
> 
> - **È fatto esplicito divieto di conservare il codice a barre bidimensionale (QR code) delle Certificazioni verdi COVID-19 sottoposte a verifica, nonché di estrarre, consultare, registrare o comunque trattare per finalità ulteriori rispetto a quelle previste dal presente articolo le informazioni rilevate dalla lettura dei QR code e le informazioni fornite in esito ai controlli**.
>
> - In caso di utilizzo di tale modalità di verifica da parte del datore di lavoro, resta salvo quanto previsto dagli articoli 88 del Regolamento (UE) 2016/679 e 113 del decreto legislativo 30 giugno 2003, n. 196.
