### ISSUE TITLE
Green pass esteri - Deroga Art. 3 DL 2 Febbraio 2022

### ISSUE THREAD

**Issue by cesaregardito** [ministero-salute/it-dgc-verificaC19-android#250]
Di recente sono state introdotte distinzioni tra GP emessi in Italia e GP emessi all'estero, e modifiche alla durata dei pass, e _on top of that_ altre deroghe.

Il comportamento attuale dell'app è strano. Al momento l'app consente 270 giorni di validità ad un GP emesso all'estero per verifica BASE, e 180 giorni ad uno italiano sempre in verifica BASE. In verifica RAFFORZATO sono invece entrambi validi 180 giorni.
In realtà l'unica distinzione sul tema andrebbe fatta tra utilizzo alla frontiera (270 gg, regole UE) e utilizzo sul territorio nazionale (180 gg, regole IT), a prescindere dal paese che ha emesso il pass.

Con il DL 2 Febbraio 2022 Art. 3 viene prescritto che un green pass da vaccinato o guarito emesso all'estero da più di 180 giorni, se considerato scaduto secondo le norme italiane, può comunque essere utilizzato come Green Pass Rafforzato sul territorio se accompagnato da un tampone negativo.

Mi permetto di suggerire una possibile soluzione a entrambi questi problemi con i pass emessi all'estero. Poiché il dato del paese di emissione è già contenuto nell'app, suggerisco:
1. Introduzione di una modalità di scansione "Viaggio EU" o "Frontiera EU", identica a "RAFFORZATO" ma che consideri validi i pass vaccinali di ciclo primario entro 270 giorni.
2. Che il check in modalità BASE o RAFFORZATO a fronte di un Green Pass da vaccinazione o guarigione scaduto da più di 180 giorni mostri NON VALIDA (red) se il pass è emesso dall'Italia, e RICHIESTO TAMPONE (orange) se il pass è emesso da un altro paese.

**Comment by rawmain** [comment]
Buonasera @cesaregardito 

> Il comportamento attuale dell'app è strano. [...]

Nessuna stranezza.

Comportamento/codice seguono & rispettano quelle che sono le disposizioni/prescrizioni, così come vengono emesse/indicate da Ministero della Salute & organi competenti.

La disposizione del periodo di accettazione 270gg - ex nuove norme UE 21/12/2021 - vale di base solo x controlli scenario TRAVEL IntraUE, che avvengono (già) appunto nella sola modalità 3G (V/R/T). Modalità corrispondente in VerificaC19 a scanmode tipologia BASE. 

In base a tali disposizioni I DGC V e R NOT_IT sono però soggetti di base alle medesime rules dei DCG IT con gli altri scanmode previsti/usati solo per scenario INTERNAL IT = nessuna differenziazione durata.

\
In tal senso il DL citato ha appunto disposto determinate deroghe a tali condizioni di base. Pertanto, il codice (_sia della verifier-app iOS che del DGC-SDK Android_) sarà adeguato di conseguenza a tali disposizioni : 

- Sbloccando la condizione di controllo differenziato start/end DGC V e R in base alla nazione di emissione DGC (_attualmente impostata/bloccata solo su BASE_) anche per gli altri scanmode ad uso Internal

- Impostando l'esito warning TEST_NEEDED per DGC V Ciclo e R NOT_IT validi con emissione >= 180gg e < 270gg per scanmode RAFFORZATA e LAVORO (_SCUOLA è fuori, visto che in tale scanmode DGC V Ciclo e R >= 120gg sono considerati NOT_VALID a priori_).

\
Per il resto, la documentazione di dettaglio sui flussi scanmode è disponibile nella repo ufficiale [IT DGC-Documentation](https://github.com/ministero-salute/it-dgc-documentation). 

Gli aggiornamenti non ancora operativi di nuovi scanmode / condizioni di controllo non sono ancora state integrati, ma il relativo work-in-progress è comunque visionabile pub dal Pull-Request tracker di tale repo.

**Comment by cesaregardito** [comment]
La stranezza che evidenziavo è che la verifica "BASE" si applica sia a situazioni sul territorio nazionale (ad esempio l'ingresso in banca) dove la durata prescritta è 180 giorni, e sia alla frontiera con travel Intra-UE con validità invece di 270 giorni. 

Senza una modalità apposita, la scansione con la durata in "BASE" impostata a 180 giorni IT ma 270 giorni NOT_IT produce inevitabilmente effetti indesiderati (un italiano con DGC V >180gg che torna in Italia da un paese UE riceverebbe "non valido", e un individuo con DGC V francese >180gg potrebbe entrare in banca senza tampone). 

Insomma da questa implementazione sembra che i DGC V emessi da stati esteri valessero 270 giorni per ogni utilizzo, anche sul territorio nazionale, quando sottoposti a verifica BASE (che ancora sussiste in varie fattispecie).

Comprendo altresì che possa essere _overkill_ sviluppare una modalità apposita per i soli controlli alla frontiera, che sono una fattispecie relativamente di nicchia. 

Per il resto tutto chiarissimo, grazie.

**Comment by rawmain** [comment]
Buongiorno @cesaregardito 

> Comprendo altresì che possa essere _overkill_ sviluppare una modalità apposita per i soli controlli alla frontiera, che sono una fattispecie relativamente di nicchia.

In virtù delle ulteriori disposizioni per quanto riguarda la distinzione di gestione in Validation Rules tra i DGC V associati a medicinal product riconosciuti EMA e non, sono in lavorazione le nuove medicinal rules con annessa valutazione di aggiunta ulteriore scanmode `ENTRY_ITALY`.

Alcune attività correlate sono già visibili pub p.es. nel [commit-tracker della feature branch `feature/entry-into-italy` del DGC-SDK Android/Kotlin](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commits/feature/entry-into-italy). 

> Per il resto tutto chiarissimo, grazie.

Prego ;) .

**Comment by cesaregardito** [comment]
Wonderful! Grazie ancora e buon lavoro.
