### ISSUE TITLE
Errore: "Execution failed for task ':dgc-sdk:kaptDebugKotlin'"

### ISSUE THREAD

**Issue by LucaDavolio** [ministero-salute/it-dgc-verificaC19-android#262]
Ho riscontrato questo errore non appena ho scaricato l'ultima versione del programma, allora ho provato a reinstallare tutto da 0 e fare il build, modificando solo i buildConfigField all'interno del build.gradle del project dgc-sdk, ma l'errore è sempre lo stesso.
Qualcuno saprebbe aiutarmi?
Grazie in anticipo.

**Comment by rawmain** [comment]
Buongiorno @LucaDavolio 

> Ho riscontrato questo errore non appena ho scaricato l'ultima versione del programma, allora ho provato a reinstallare tutto da 0 e fare il build, modificando solo i buildConfigField all'interno del build.gradle del project dgc-sdk, ma l'errore è sempre lo stesso.

Come puoi vedere [qui](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/search?q=kaptDebugKotlin&type=issues), tale errore si presenta se/quando vi sono problemi con la cache o si aggiorna il plugin kotlin usato dal progetto, fidandosi del suggerimento di Android Studio (_vanno ignorati sia tale avviso che quello relativo all'aggiornamento di gradle_).

Se hai aggiornato il/i plugin di progetto, cancella e ricrea il progetto da zero. Altrimenti, verifica con invalidate cache + restart.

**Comment by LucaDavolio** [comment]
Buongiorno @rawmain

Ho provato sia a reinstallare completamente il progetto e Android Studio (anche su di una macchina appena ripristinata per essere sicuro), sia ad utilizzare invalidate cache + restart, ma nulla.
È possibile che il plugin di kotlin venga aggiornato in automatico senza chiedere conferma? 
Perché ogni volta che apro il progetto mi chiede di aggiornare quello del Gradle ma non quello kotlin

**Comment by rawmain** [comment]
Buongiorno @LucaDavolio 

> È possibile che il plugin di kotlin venga aggiornato in automatico senza chiedere conferma?

Android Studio aggiorna automaticamente i plugin di progetto :

- In fase di update versioni se non si è provveduto a deselezionare gli aggiornamenti dei `plugin from configured hosts` nelle opzioni di configurazione del processo di aggiornamento. Se p.es. si effettua l'aggiornamento a Bumblebee | 2021.1.1 Patch 1 da release precedente, compare selezionato l'aggiornamento plugin a Kotlin release 1.6.0, che appunto va deselezionato.

- se/quando non rileva override/dichiarazione di versione per i plugin progetto - perché assenti o per errore in fase di sync/parse

Dato che si tratta di un tuo problema specifico (non generico) di configurazione/impostazione ambiente di build, suggerisco di procedere per gradi.

Scarica dall'[archivio release Android Studio](https://developer.android.com/studio/archive) una vecchia versione 4.x (4.2.1 o precedente), quindi configura e procedi con build del progetto.

Solo una volta che hai verificato che siano ok le tue impostazioni & i processi di build delle varianti, allora puoi procedere con update - direttamente dalla istanza progetto - a Bumblebee (_Chipmunk e Dolphin non sono ancora in ramo Stable_), tenendo ovviamente conto di deselezionare gli aggiornamenti automatici dei plugin in fase di update.
