### ISSUE TITLE
[Feature Request] Cambiare il popup di scelta tipo verifica con un'activity a sé

### ISSUE THREAD

**Issue by vixrt** [ministero-salute/it-dgc-verificaC19-android#265]
![img_vc19 - Copia](https://user-images.githubusercontent.com/65950712/155529813-940d296c-5441-4595-afc3-e6a3d2df5250.jpg)

Attualmente si può scegliere fra 6 tipi di verifica, presentando all'utente un popup decisamente brutto. 

Arrivati a questo punto, visto anche che alcune risoluzioni schermo di alcuni dispositivi sono veramente basse, direi che è oppurtuno valutare, anche in vista di eventuali ingressi nelle tipologie di verifica, di spostare la selezione della verifica in una activity separata.
https://developer.android.com/reference/android/app/Activity

Nell'activity separata sarà più facile, graficamente, illustrare le varie modalità, descrivere cosa comprende ciascuna, ecc...

https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/143

**Comment by rawmain** [comment]
Buonasera @vixrt 

> Attualmente si può scegliere fra 6 tipi di verifica, presentando all'utente un popup decisamente brutto.

La PR #273 (merged 4h fa) introduce una nuova gestione della finestra per la selezione scanmode.

- Supporto barra di scorrimento verticale, in modo da consentire la visualizzazione anche su schermi con bassi valori/rapporti per risoluzione e DPI 

- Aggiunta pulsante per conferma manuale post-selezione (prima la conferma avveniva automaticamente alla selezione dello scanmode)

- Le opzioni scanmode sono visualizzate con solo iniziale e nome (e.g. B - Base, R - Rafforzata, etc.) = la descrizione appare solo sotto l'opzione selezionata

**Comment by vixrt** [comment]
Buongiorno @rawmain 

Sono contento sia già stato fatto merge della funzionalità, attendo la pubblicazione su Google Play Store e poi chiudo

Grazie
