### ISSUE TITLE
I got a Italy Green Pass, it is verified from the German official App CovPass, but it is denied from VerificC19 

### ISSUE THREAD

**Issue by yzhang666** [ministero-salute/it-dgc-verificaC19-android#272]
I have an Italy Green Pass, and I decode the QR code, check the UVCI from https://get.dgc.gov.it/v1/dgc/settings; it is not on the blacklist. Then, I digest the UVCI, and check the records from https://get.dgc.gov.it/v1/dgc/drl, it is not on the list either,

The owner had the booster dose (all of the doses are Spikevax and Vaxzevria), but unfortunately, he got sick a few days ago. The trick thing is, from the German official App CovPass, if you use the app to scan the code, it is verified with green; but if to use the Italian VerificC19, it shows the gree pass is denied with red.

My question is, besides the above two blacklists, does the Italian app use any additional methods (or codes) to check the validity of a QR code?

**Comment by rawmain** [comment]
> I have an Italy Green Pass, and I decode the QR code [...]

Multi-posting is a bad thing. Please close this thread & continue in the other one you've opened in the DGC-SDK repo.

https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/147#issuecomment-1056883803
