### ISSUE TITLE
QRCode di test per esenzioni

### ISSUE THREAD

**Issue by lpomi** [ministero-salute/it-dgc-verificaC19-android#284]
Buonasera, 
è possibile avere i qr code di test per le Esenzioni ?
Green Pass di tipo CUEV (esenzione digitale in vigore dal 7 febbraio 2022 )
Abbiamo visto che nel repository ci sono alcuni qr code di test ma non più aggiornati e non mi sembra per la verifica delle esenzioni.

https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/IT

Grazie mille

* Source File:
* Line(s):
* Question:

**Comment by rawmain** [comment]
Buongiorno @lpomi 

> è possibile avere i qr code di test per le Esenzioni ? Green Pass di tipo CUEV (esenzione digitale in vigore dal 7 febbraio 2022 ) Abbiamo visto che nel repository ci sono alcuni qr code di test ma non più aggiornati e non mi sembra per la verifica delle esenzioni.

I certificati digitali di esenzione vaccinale (e) non rientrano in schema DGC EU-DCC (v/r/t). Ecco perché non sono/saranno disponibili nelle repository sample EU-DCC - né in testdata (DSC TST Environment) né in quality assurance (DSC ACC Environment).

Dato che lo [schema JSON dei CRT E](https://github.com/ministero-salute/it-dgc-documentation/blob/master/EXEMPTIONS.md) si base comunque su quello usato per DGC, in assenza di sample reali è possibile generare sample di test, riprendendo p.es. la struttura dei DGC R di guarigione & sostituendo il campo r con e.

Vedasi HCert claim/payload modificato di esempio (_ripreso dal curated sample DGC R IT in QA_) : 

```
{
  "e": [
    {
      "ci": "01IT2AB185B1A31D4842BCB6410A661842F1#1",
      "co": "IT",
      "df": "2022-03-09",
      "du": "2022-08-16",
      "fr": "2022-02-21",
      "is": "Ministero della Salute",
      "tg": "840539006"
    }
  ],
  "dob": "1981-01-01",
  "nam": {
    "fn": "Verdi Rossi",
    "gn": "Mario Luigi",
    "fnt": "VERDI<ROSSI",
    "gnt": "MARIO<LUIGI"
  },
  "ver": "1.3.0"
}
```

Ovviamente, i sample generati CRT E sono validabili solo in ambienti di test (_ACC / TST se autorizzati ad uso firme o propri/privati_) e non di produzione.
