### ISSUE TITLE
Versione 1.2.10

### ISSUE THREAD

**Issue by LucaDavolio** [ministero-salute/it-dgc-verificaC19-android#291]
Salve,
ho visto che per i dispositivi Android è disponibile da lunedì scorso la versione 1.2.10, però il source code è ancora alla 1.2.9.
Ci sono dei problemi con l'ultima versione di Android o state aspettando rilasciarla anche per IOS prima di renderla disponibile anche qui?
Grazie in anticipo per la risposta

**Comment by rawmain** [comment]
Buongiorno @LucaDavolio 

> ho visto che per i dispositivi Android è disponibile da lunedì scorso la versione 1.2.10, però il source code è ancora alla 1.2.9.

La release 1.2.10 - build 671 Android era una build intermedia (con bugfix minimi) & è stata caricata il 19 Marzo per la pubblicazione solo sul Google PlayStore, non su Huawei AppGallery.

Oggi è stata pubblicata la release 1.2.11 - _sia per Android (build 673) su Huawei AppGallery + Google PlayStore che per iOS su Apple AppStore_ .

Tale release 1.2.11 integra non solo i bugfix della release 1.2.10, ma anche i commit approvati in develop branch fino al 28 Marzo - ved. rimozione della tipologia di verifica Lavoro (_scanmode WORK_) in conformità a [DL 24/2022](https://www.gazzettaufficiale.it/eli/id/2022/03/24/22G00034/sg).

I commit in develop branch Android app/UI e DGC-SDK / iOS app successivi al 28 Marzo - relativi alla rimozione anche della tipologia di verifica Studenti (_scanmode SCHOOL_) - non sono infatti stati incorporati nelle storerelease 1.2.11 attualmente pubblicate, ma verranno integrati successivamente.

**Comment by LucaDavolio** [comment]
Ottimo, quindi anche la release version del source code passerà alla 1.2.11 entro breve?

**Comment by rawmain** [comment]
Buongiorno @LucaDavolio 

> Ottimo, quindi anche la release version del source code passerà alla 1.2.11 entro breve?

Per quanto riguarda l'aggiornamento pub dei release-tracker, non è escluso a questo punto che ciò avvenga solo a completamento di tutte le modifiche previste da DL 24/2022 = contestuale a finalizzazione successiva storerelease con disabilitazione anche della tipologia di verifica Studenti (scanmode SCHOOL) - ved. anche [circolare 410 del Ministero dell'Istruzione](https://www.miur.gov.it/documents/20182/6735034/Circolare+n.+410+del+29+marzo+2022.pdf/bdf26def-731c-660b-0f87-2dc04fd5bc87?version=1.0&t=1648620866961).

Nel frattempo, è comunque possibile replicare la situazione transitoria - _aspetto/funzionalità_ - del codice Android storerelease 1.2.11 - build 673, utilizzando il codice attualmente approvato in develop branch app/UI + DGC-SDK con le modifiche del caso, onde escludere i commit successivi al 28 Marzo / relativi alla disabilitazione della verifica Studenti : 

1. Revert delle modifiche del commit [`866ce18`](https://github.com/ministero-salute/it-dgc-verificaC19-android/commit/866ce189fe63e766a21a27c001a6f45aef13cbf7) (_disabilitazione visibilità/scelta SCHOOL scanmode in app/UI_)

2. Bump in `app/build.gradle` di  `versionCode` - `versionName` = `665` - `"1.2.9"` -> `673` - `"1.2.11"` 

3. Revert delle modifiche del commit [`3f07841`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/3f0784180f97eec61c62964a3f9d8c78fa9b5995) (_rimozione SCHOOL scanmode da DGC-SDK_)

**Comment by LucaDavolio** [comment]
Sapresti dirmi invece se con la `1.2.12 `sono state applicate le modifiche riguardanti la _SCHOOL scanmode_ e qual è il `versionCode` del `versionName 1.2.12`?
Perché vedo che la _release version_ qui è ancora la `1.2.9`

**Comment by rawmain** [comment]
Ciao @LucaDavolio 

> Sapresti dirmi invece se con la `1.2.12 `sono state applicate le modifiche riguardanti la _SCHOOL scanmode_ e qual è il `versionCode` del `versionName 1.2.12`? 

La storerelease 1.2.12 aggiunge - rispetto alla precedente 1.2.11 - la rimozione anche della tipologia di verifica Studenti (_scanmode School_) sia dal codice app/UI che da quello DGC-SDK .

Gli aggiornamenti pub dei release-tracker di app/UI e DGC-SDK sono ancora in WIP. Nel frattempo, è comunque possibile replicare la situazione transitoria - _aspetto/funzionalità_ - del codice Android storerelease corrente tramite :

- allineamento a storico commit in branch develop delle repo app/UI e DGC-SDK sino al 30/03 incluso

- app/build.gradle bump -> `versionCode 674` e `versionName "1.2.12"`

- sdk/build.gradle bump -> `buildConfigField "String", "SDK_VERSION", "\"1.1.7\""`

**Comment by LucaDavolio** [comment]
Scusa l'insistenza, sapresti invece dirmi cosa è stato aggiunto o rimosso con la versione `1.3.0`?
La nuova versione verrà inserita anche qui nel source code? Altrimenti potresti dirmi il `versioCode `del `versionName 1.3.0`?

**Comment by rawmain** [comment]
Ciao @LucaDavolio 

> cosa è stato aggiunto o rimosso con la versione `1.3.0`? La nuova versione verrà inserita anche qui nel source code? Altrimenti potresti dirmi il `versioCode `del `versionName 1.3.0`?

La storerelease 1.3.0 aggiunge - rispetto alla precedente 1.2.12 - il supporto per il riconoscimento delle regole addizionali (_ancora non pubblicate in Validation Rules_) per il controllo nella modalità **Ingresso IT** di DGC di intestatari minorenni (_ved. commit di riferimento [`93e3b64`](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/93e3b64e1d5016f0887b1a153147b35a51d06954) in repo DGC-SDK_).

Gli aggiornamenti pub dei release-tracker di app/UI e DGC-SDK sono ancora in WIP. Nel frattempo, è comunque possibile replicare la situazione transitoria - _aspetto/funzionalità_ - del codice Android storerelease corrente tramite :

- allineamento a storico commit in branch develop delle repo app/UI e DGC-SDK sino al 05/04 incluso

- app/build.gradle bump -> `versionCode 677` e `versionName "1.3.0"`

- sdk/build.gradle bump -> `buildConfigField "String", "SDK_VERSION", "\"1.1.8\""`
