### ISSUE TITLE
When first name and/or last name are too long, they don't fit the width of the screen

### ISSUE THREAD

**Issue by astagi** [ministero-salute/it-dgc-verificaC19-android#48]
## Describe the bug

When first name and/or last name are too long, they don't fit the width of the screen

## Expected behaviour

First name and last name should fit the screen width and be clear

## Steps to reproduce the issue

Try to scan a certificate that contains a long first name or last name 

## Technical details

- Host Machine OS: Android

## Possible Fix

Allow first name and last name to stay in more than one line.

**Comment by danielsp3000** [comment]
@astagi done in #52 and merged in #50

**Comment by astagi** [comment]
thank you @danielsp3000
