### ISSUE TITLE
QR code reading not reliable

### ISSUE THREAD

**Issue by enricomiletto** [ministero-salute/it-dgc-verificaC19-android#73]
## Describe the bug

When compared with the Swiss or the [Dutch ](https://play.google.com/store/apps/details?id=nl.rijksoverheid.ctr.verifier)DCG verifier apps, VerificaC19 is error-prone and very slow in reading the QR codes when in nonoptimal circumstances.

When the QR code in frame is slightly rotated or not perfectly centred the app can take many seconds or even totally fail to read the QR code at all.
And even when it does manage to read the QR code it often (in about 1 in 5 cases from my experience) fails to read it correctly and shows the "Certificazione non valida" message.

This is a problem because in some situations (for example at the entrance of big events) it can be difficult and time consuming to frame the code correctly or retry scanning the QR code after it was wrongfully read as invalid.

## Expected behaviour

The QR code gets read and verified in 1 sec. or less and independently of how the QR code is rotated, just like it happens with Verifier apps of other countries.

## Steps to reproduce the issue

1. Tap on "Avvia Scansione"
2. Frame the QR at an inclination above 30°
3. The App will not manage to read the QR code at all or read it incorrectly with a relatively high probability

## Technical details

- Host Machine OS Android 10:

**Comment by enricomiletto** [comment]
Uploading WhatsApp Video 2021-07-26 at 15.45.41_Trim.mp4…

**Comment by Signoo** [comment]
Seems like they're using different libraries for QR detection.
[Italian version](https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/codeReader/CodeReaderFragment.kt#L33);
[Dutch version](https://github.com/minvws/nl-covid19-coronacheck-app-android/blob/main/qrscanner/src/main/java/nl/rijksoverheid/ctr/qrscanner/QrCodeScannerFragment.kt#L32);

Doesn't look like [zxing](https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/google/zxing/integration/android/IntentIntegrator.java) has other options to make it faster.

**Comment by enricomiletto** [comment]
Hey @Signoo, I see.

The [swiss version](https://github.com/admin-ch/CovidCertificate-App-Android/blob/cbeb10d2a003ebdab6a3660aa32f88654072ac13/common/src/main/java/ch/admin/bag/covidcertificate/common/qr/QRCodeAnalyzer.kt#L17) seems to be using zxing too, but it doesn't have problems handling rotated qr codes.

So maybe they did find a way to solve this problem while still using zxing.

**Comment by Signoo** [comment]
@enricomiletto just looked a bit more into the code:
The italian version uses a wrapper built around zxing: [https://github.com/journeyapps/zxing-android-embedded](zxing-android-embedded) which doesn't seem to be customizable.
The swiss version uses zxing directly, it [parses](https://github.com/CameraKit/camerakit-examples/blob/master/barcode-scanner/app/src/main/java/app/camerakit/barcodes/ScannerActivity.kt#L36) each camera frame, generates a [PlanarYUVLuminanceSource](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/PlanarYUVLuminanceSource.java) which is then used by [HybridBinarizer](https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/common/HybridBinarizer.java) to generate the bitmap. Guess that's why the detection is faster.

It should be possible to implement the same in the italian version.

**Comment by enricomiletto** [comment]
I just discovered that the app also reads other types of barcodes. If one scans the barcode on a book, for example, the app will read it and then of course show the "Certificazione non valida" message. This is because standard ZXing can read 17 different types of 1D and 2D barcodes.

This explains why the app **often fails to read correctly real DCC QR codes**; it's not that the app reads the QR code wrong (which is something very very unlikely to happen given the checksums and error correction in QR codes) but it "finds" a pattern inside the QR code matrix which corresponds to some other barcode standard, this of course leads to invalid data.

This is exactly the same behaviour that the Barcode Scanner app (based on ZXing) has as you can see from the screenshot below

![WhatsApp Image 2021-07-29 at 16 32 26](https://user-images.githubusercontent.com/80707578/127513260-c2f5d687-cefb-4452-aef5-1b32e1919674.jpeg)

To solve this issue, the app should exclusively look for QR codes (just like the Swiss version which also uses ZXing does) and this will solve the issue of real DCC QR codes leading to the "Certificazione non valida" message.

**Comment by enricomiletto** [comment]
The cool/fun side effect of this is that you can validate DCC's that are stored in a barcode different from a QR code, for example 
a Data Matrix (which is also supported by ZXing).  :-P

https://user-images.githubusercontent.com/80707578/127520234-f00aa662-00b8-406b-ad56-7074cacdf88a.mp4

**Comment by astagi** [comment]
@Signoo @enricomiletto thanks for reporting this issue and for videos. We're working to improve scanning experience (especially on removing scanning errors), some updates on this will come in the next version!

**Comment by enricomiletto** [comment]
@astagi I tried the new update today, and the scanning definetly works **much much** better now.
The app now reads QR-codes that are **rotated** more reliably and quicker (YAY! 👏)

That said:
- the app **still reads non-QR** types of codes (like EAN, Data Matrix ecc.) and shows the (new) "Errore di lettura" message.
 In my opinion, the app should just **ignore them** and remain in the **viewfinder** screen and keep looking for QR codes.
 The **errore di lettura** message should just be shown when the app **reads a QR code** that's **not a DCC**
- This also means that the app still **occasionaly** (definetly way less often than before and only at specific angles) **misreads a QR code** as it finds a pattern matching some **1D barcode** in the **matrix** of the QR code. 
I cannot prove that this is the **cause of the misread QR codes** but it seems the **most plausible explanation to me** (given that the Barcode Scanner app has the same behaviour and that it is generally **pretty difficult** to misread a QR code otherwise)
- The app only reads the QR code only if it's **fully** (all 4 edges) **inside the square** that's not greyed out in the viewfinder screen. I understand the need to **guide the user** to frame the code in a **decent way**, but the app shoould **still be able** to read the code if a **minute portion** of the code in **not inside** the "inner square"
-

**Comment by enricomiletto** [comment]
The latest update of the app (1.0.3) has **fixxed all the major issues** mentioned in this GitHub issue. 

The only (minor) "problem" remaining is that the app only reads the QR code when it's fully inside of the inner/not greyed out square; just a small portion of the QR code that's outside the square suffices for the app not to read it
Other apps (i've tested personally the swiss and the dutch one), while they still have a similar "square" to help the user better frame the code, still read codes if they're not inside that square.

**Comment by astagi** [comment]
@enricomiletto thank you for this update and sorry for my late response, I'm currently on vacation! I'm very happy to hear this, I think we can close this issue and open an "enhancement" to improve QR code reading process, WDYT?

**Comment by enricomiletto** [comment]
@astagi Yes I totally agree.
