### ISSUE TITLE
not compile error Type mismatch: inferred type is ByteArray? but ByteArray was expected 

### ISSUE THREAD

**Issue by uganof** [ministero-salute/it-dgc-verificaC19-android#75]
Hi,
when I compile in Android Studio v. 4.2.2, exit with error:

it-dgc-verificaC19-android\app\src\main\java\it\ministerodellasalute\verificaC19\ui\main\verification\VerificationViewModel.kt: (96, 51): Type mismatch: inferred type is ByteArray? but ByteArray was expected

what can I do?

all necessary sources are updated by github

thanks

**Comment by astagi** [comment]
Hi @uganof try to update DGCA-APP-CORE-ANDROID repository to the latest commit, seems to be fixed there.

```kt
interface CompressorService {
    fun decode(input: ByteArray, verificationResult: VerificationResult): ByteArray?
}
```
