### ISSUE TITLE
Use higher resolution image for splash screen logo

### ISSUE THREAD

**Issue by enricomiletto** [ministero-salute/it-dgc-verificaC19-android#76]
## Current Implementation

The logo that is shown on the splash screen is low res

## Suggested Enhancement

Use a higher resolution raster file, or a vector format file (like SVG)

## Expected Benefits

The app will look more polished

**Comment by astagi** [comment]
@enricomiletto could you share a screenshot and device details in order to reproduce it?

**Comment by enricomiletto** [comment]
@astagi thanks for taking the time to respond.

The "issue" is device independent. It's really just the file `app/src/main/res/drawable/logo_splash.png` that's a little low resolution

**Comment by astagi** [comment]
Oh you're right @enricomiletto ! The team is working on a new version with a brand new UI I'll ask them to place a better resolution splash screen. Thank you

**Comment by astagi** [comment]
@Light2288 please could you provide a hi-res image for the splash screen in the restyling branch?

**Comment by enricomiletto** [comment]
The latest version (1.1.0) with the new UI still uses the same low res PNG file.
Furthermore the logo now also shows up in the upper left corner on the main screen of the app and is also there very low res.

I do of course understand that I'm a little bit nitpicking here, but it seems to me like a very easy fix which would make the app look better

**Comment by astagi** [comment]
It's easy to fix @enricomiletto I'm still waiting for hi-res images from designers. I'll try to ping them again today.
