### ISSUE TITLE
Standardised Name is not used in the Verification fragment

### ISSUE THREAD

**Issue by DimPaDev** [ministero-salute/it-dgc-verificaC19-android#82]
## Describe the bug

When a QR code is being verified and the app shows the personal data of the user only the original type of the name is visible.
Instead , ( like similar apps from other european countries do ) the app should also show the STANDARDISED type of the name and the last name. This will be useful when the original name and the original last name of the user is using non-latin characters ( for example a person with two nationalities ) and the verification process through an identity card from an authority in Italy will be easier. 

## Expected behaviour

The app should also show the STANDARDISED type (with latin characters) of the name and the last name in the verification fragment. 

## Possible Fix

In order to do that, only one line should be edited : 

[https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationFragment.kt](https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/app/src/main/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationFragment.kt#L247)

LINE 247 --> 

FROM :

`binding.nameStandardisedText.text = ""`

TO : 

`binding.nameStandardisedText.text = person.standardisedFamilyName.plus(" ").plus(person.standardisedGivenName)`

**Comment by enricomiletto** [comment]
You could also consider implementing something like what @admin-ch did. 
The first and last name fields show the name in the original language charachters, but lower there's a string showing how the name would appreat on the last line of the MRZ (machine readable zone) of the ID card/passport of the DCC's holder

![WIN_20210802_23_59_46_Pro_LI](https://user-images.githubusercontent.com/80707578/127929800-052f296f-565b-4dd5-a579-4884b0cddfd9.jpg)
