### ISSUE TITLE
About sdk 26+

### ISSUE THREAD

**Issue by gypsymauro** [ministero-salute/it-dgc-verificaC19-android#85]
Why this limitation? there are different green pass verification apps 
(like the swiss one https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.verifier&hl=it&gl=US) 
that works on older version of android, and correctly displays green pass info, can you make this app available for older devices?

**Comment by astagi** [comment]
Hi @gypsymauro we're working to make app working on older devices (SDK 24+).

**Comment by gypsymauro** [comment]
can we have a release date for this "fix"?

**Comment by astagi** [comment]
@gypsymauro team is working on this issue, it's on top of our priorities. Also a PR has been opened to achieve that https://github.com/ministero-salute/it-dgc-verificaC19-android/pull/71

**Comment by lpomi** [comment]
The fix for SDK 25 was released ?
