### ISSUE TITLE
Unable to scan - the app raises a dialog error saying that it needs Internet conenctivity notwithstanding the phone is connected

### ISSUE THREAD

**Issue by vincenzoiovino** [ministero-salute/it-dgc-verificaC19-android#86]
I click on "avvia scansione" (start scan) and hte app raises a dialog saying "Impossibile scansionare, l'applicazione deve connettersi alla rete almeno una volta per essere utilizzata" (unable to scan, the app needs internet connection at least once to be used).
The phone is connected to internet.
Debugging it, it seems it tries unsuccessfully to access some online resources on sogei.it and it gets access denied.
All authorizations are provided in the settings.
this problem does not occur with the EU and other verification apps.
Any clue?

**Comment by vincenzoiovino** [comment]
> I click on "avvia scansione" (start scan) and hte app raises a dialog saying "Impossibile scansionare, l'applicazione deve connettersi alla rete almeno una volta per essere utilizzata" (unable to scan, the app needs internet connection at least once to be used).
> The phone is connected to internet.
> Debugging it, it seems it tries unsuccessfully to access some online resources on sogei.it and it gets access denied.
> All authorizations are provided in the settings.
> this problem does not occur with the EU and other verification apps.
> Any clue?

Using the servers for the "release" version, it works. It seem the servers set in the debug version are not available.

**Comment by EdossProject** [comment]
When I try to install the release version it tells me it cannot be installed.

**Comment by Enrico204** [comment]
> When I try to install the release version it tells me it cannot be installed.

Please open a new issue for this, and include all information you have (O.S. version, if you installed the app from the play store or not, whatever information that can help others to understand and possibly reproduce your issue)

**Comment by astagi** [comment]
Agree with @Enrico204 , @EdossProject please open a new issue for that, it may depends on your android version or if you have the app already installed from play store.

**Comment by wolfcod** [comment]
I'm using VerificaC19 on a dual sim phone, with internet enabled on second sim.. same error. I disabled the first sim and it's works fine.
