### ISSUE TITLE
All test QR codes on the main EU dgc's repository generated by the Italian's Team do NOT verify

### ISSUE THREAD

**Issue by vincenzoiovino** [ministero-salute/it-dgc-verificaC19-android#87]
## Describe the bug

I tested  all QR codes available here: https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/IT
The verification fails for ALL of them.
Notwithstanding: 1) I can verify other QR codes (not present in the list above) and 2) other verification apps from UE (and not only) can verify the QR codes given in the link above.

## Additional info
It seems that after the instruction "val key = db.keyDao().getById(kid)" of getCertificate in VerifierRepository, key is null.
What does it mean?

**Comment by astagi** [comment]
Hi @vincenzoiovino these certificates are only for test purpose and don't have a valid signature. As you can see some apps are currently showing the information taken from DCC payload, we're working on a new UI to make those data available for VerificaC19 too.

**Comment by vincenzoiovino** [comment]
> Hi @vincenzoiovino these certificates are only for test purpose and don't have a valid signature. As you can see some apps are currently showing the information taken from DCC payload, we're working on a new UI to make those data available for VerificaC19 too.

So, the bug would be in the EU and other National apps?
The EU official app and the Swiss one Covid Certificate, only to mention some, do verify successfully the above codes.
What is going on?

**Comment by astagi** [comment]
@vincenzoiovino I tried Covid Check Swiss app and I get this

![IMG_0096](https://user-images.githubusercontent.com/537363/127896328-3980a673-453a-4cf8-ae73-8c3966213992.PNG)
![IMG_0098](https://user-images.githubusercontent.com/537363/127896333-73dfdaa3-c052-44f1-b4fe-2440622f1cb3.PNG)

**Comment by vincenzoiovino** [comment]
> @vincenzoiovino I tried Covid Check Swiss app and I get this
> 
> ![IMG_0096](https://user-images.githubusercontent.com/537363/127896328-3980a673-453a-4cf8-ae73-8c3966213992.PNG)
> ![IMG_0098](https://user-images.githubusercontent.com/537363/127896333-73dfdaa3-c052-44f1-b4fe-2440622f1cb3.PNG)

wit the EU app I get:
![WIN_20210802_19_06_48_Pro (2)](https://user-images.githubusercontent.com/41876613/127898604-81f37c22-8578-47d7-9571-77988b0ce4d2.jpg)

and the Swiss Covid Cert app I get:
![image](https://user-images.githubusercontent.com/41876613/127898709-3b56465a-15bf-45d9-8c5b-b05e42ec84c2.png)

However it only later says the sig is invalid.
So the issue would be only in the EU app that shows green sign.

**Comment by astagi** [comment]
@vincenzoiovino yes this behaviour only affects the EU app. I'll close #229 as well, thanks for having reported this problem!
