### ISSUE TITLE
Fake QR codes for testing

### ISSUE THREAD

**Issue by aiotech-pub** [ministero-salute/it-dgc-verificaC19-android#94]
I want to know if are available QR codes to test the app and where I can found them to download.

**Comment by barsa-net** [comment]
There is a folder `assets` used by unit tests: https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/develop/app/src/test/assets

They are used here:
https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/d3a17adf9dd096405309c8646e11a737753b6922/app/src/test/java/it/ministerodellasalute/verificaC19/utils/mock/ServiceMocks.kt#L27-L87

And then here:
https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/d3a17adf9dd096405309c8646e11a737753b6922/app/src/test/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModelTest.kt#L133-L169

**Comment by Lazza** [comment]
https://dgc.a-sit.at/ehn/

**Comment by aiotech-pub** [comment]
> 
> 
> There is a folder `assets` used by unit tests: https://github.com/ministero-salute/it-dgc-verificaC19-android/tree/develop/app/src/test/assets

these are mocks I mean if you have fake QR to be used in user testing or functional testing. If you do not have I could make fake QR codes starting by the mocks (supposing the mocks contain all the data a QR code contains) but I need the QR parameters to be sure to produce a complaint QR code.
> 
> They are used here:
> 
> https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/d3a17adf9dd096405309c8646e11a737753b6922/app/src/test/java/it/ministerodellasalute/verificaC19/utils/mock/ServiceMocks.kt#L27-L87
> 
> And then here:
> 
> https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/d3a17adf9dd096405309c8646e11a737753b6922/app/src/test/java/it/ministerodellasalute/verificaC19/ui/main/verification/VerificationViewModelTest.kt#L133-L169

**Comment by barsa-net** [comment]
@aiotech-pub sorry, but I'm not a developer nor a mantainer of this application, I was just searching the same infos myself and pointed you out to my findings.

**Comment by aiotech-pub** [comment]
> 
> 
> @aiotech-pub sorry, but I'm not a developer nor a mantainer of this application, I was just searching the same infos myself and pointed you out to my findings.

Ah OK you were in the same black sea I was. Anyway I found themo, just four but I found them.

**Comment by aiotech-pub** [comment]
I found the QR codes by myself: https://github.com/eu-digital-green-certificates/dgc-testdata contains test data for every EU state more or less.
