### ISSUE TITLE
Responsabile approvazione risoluzione bug e richieste di modifica

### ISSUE THREAD

**Issue by aiotech-pub** [ministero-salute/it-dgc-verificaC19-android#97]
Vorrei sapere nome e cognome di chi ha la responsabilita' di approvare/accettare o di rigettare le richieste di modifica e quali bug risolvere o non riconoscere come tali di questa app nota come Verifica C19.
Grazie.

**Comment by gianluca-mascolo** [comment]
Buonasera,
per conoscere i codeowners è sufficiente fare riferimento al file https://github.com/ministero-salute/it-dgc-verificaC19-android/blob/develop/CODEOWNERS per cui può fare riferimento a https://github.com/it-eucert-team
Saluti
Gianluca

**Comment by aiotech-pub** [comment]
Grazie

**Comment by aiotech-pub** [comment]
No, non sono stato chiaro... chi e' il responsabile italiano, chi ha deciso che l'app poteva essere pubblicata e scaricata dagli utenti e chi ha il potere decisonile di accettare o meno la segnalazione di bug la loro correzione o meno e di accettare segnalazioni e richieste di modifica ecc ecc

**Comment by Enrico204** [comment]
Sono le persone di quel team.
